export type Protein = "chicken" | "beef" | "fish" | "egg" | "legume" | "veg" | "tofu";
export type Cuisine = "mediterranean" | "mexican" | "asian" | "comfort" | "fresh" | "italian";
export type DietTag =
  | "vegetarian" | "vegan" | "glutenFree" | "dairyFree" | "lowSodium"
  | "diabetesFriendly" | "highProtein" | "lowCarb" | "kidFriendly" | "light";
export type GoalTag = "fast" | "cheap" | "healthy" | "useWhatIHave" | "protein" | "lowCalorie" | "easy";

export interface RecipeTemplate {
  id: string;
  category: "main" | "snack";
  name: { es: string; en: string };
  description: { es: string; en: string };
  emoji: string;
  timeMinutes: number;
  difficulty: "Easy" | "Medium" | "Hard";
  baseServings: number;
  baseCostUSD: number;
  baseCalories: number;
  protein: Protein;
  cuisine: Cuisine;
  dietTags: DietTag[];
  goalTags: GoalTag[];
  ingredients: { name: string; category: string; qty: string }[];
  steps: { es: string[]; en: string[] };
  tips: { es: string[]; en: string[] };
  healthBenefits: { es: string[]; en: string[] };
  pairing: { es: PairingSuggestion; en: PairingSuggestion };
}

export interface PairingSuggestion {
  side: string;
  dessert: string;
  drink: string;
}

export const recipes: RecipeTemplate[] = [
  {
    id: "chicken-stirfry",
    category: "main",
    name: { es: "Pollo salteado estilo asiático", en: "Asian-style chicken stir fry" },
    description: { es: "Pollo salteado a fuego fuerte con vegetales crocantes y salsa de soja.", en: "High-heat chicken stir fry with crisp vegetables and soy glaze." },
    emoji: "🥢",
    timeMinutes: 20,
    difficulty: "Easy",
    baseServings: 2,
    baseCostUSD: 7,
    baseCalories: 480,
    protein: "chicken",
    cuisine: "asian",
    dietTags: ["dairyFree", "highProtein"],
    goalTags: ["fast", "protein", "easy"],
    ingredients: [
      { name: "Pollo", category: "Carnes", qty: "400g" },
      { name: "Cebolla", category: "Verduras", qty: "1" },
      { name: "Zapallito", category: "Verduras", qty: "1" },
      { name: "Salsa de soja", category: "Almacén", qty: "3 cdas" },
      { name: "Arroz", category: "Almacén", qty: "1 taza" },
    ],
    steps: {
      es: [
        "Cortá el pollo en tiras finas.",
        "Calentá una sartén grande a fuego fuerte con un poco de aceite.",
        "Saltea el pollo 4-5 minutos hasta dorar.",
        "Agregá cebolla y zapallito, saltea 3 minutos más.",
        "Sumá la salsa de soja y cociná 2 minutos.",
        "Serví sobre arroz caliente.",
      ],
      en: [
        "Cut the chicken into thin strips.",
        "Heat a large pan on high heat with a bit of oil.",
        "Sear the chicken 4-5 minutes until golden.",
        "Add onion and zucchini, stir-fry 3 more minutes.",
        "Pour in the soy sauce and cook 2 minutes.",
        "Serve over hot rice.",
      ],
    },
    tips: {
      es: ["Fuego fuerte todo el tiempo: eso le da el sabor a salteado.", "Si no tenés zapallito, cualquier verdura crocante funciona."],
      en: ["Keep the heat high the whole time — that's what gives it the stir-fry flavor.", "No zucchini? Any crisp vegetable works."],
    },
    healthBenefits: {
      es: ["Alta en proteína magra para mantener la energía todo el día.", "Los vegetales salteados aportan vitamina C y fibra."],
      en: ["High in lean protein to keep your energy steady all day.", "The stir-fried vegetables add vitamin C and fiber."],
    },
    pairing: {
      es: { side: "Pepino en rodajas con sésamo.", dessert: "Gajos de naranja o helado de mango.", drink: "Un vino blanco seco (Sauvignon Blanc) o, sin alcohol, limonada bien fría." },
      en: { side: "Sliced cucumber with sesame.", dessert: "Orange wedges or mango sorbet.", drink: "A dry white wine (Sauvignon Blanc), or fresh lemonade if you skip alcohol." },
    },
  },
  {
    id: "mediterranean-chicken-bowl",
    category: "main",
    name: { es: "Bowl mediterráneo de pollo", en: "Mediterranean Chicken Bowl" },
    description: { es: "Pollo grillado con vegetales frescos, un bowl liviano y equilibrado.", en: "Grilled chicken with fresh vegetables, a light and balanced bowl." },
    emoji: "🥗",
    timeMinutes: 25,
    difficulty: "Easy",
    baseServings: 4,
    baseCostUSD: 12,
    baseCalories: 520,
    protein: "chicken",
    cuisine: "mediterranean",
    dietTags: ["glutenFree", "highProtein", "light"],
    goalTags: ["healthy", "protein"],
    ingredients: [
      { name: "Pollo", category: "Carnes", qty: "500g" },
      { name: "Tomate", category: "Verduras", qty: "2" },
      { name: "Cebolla", category: "Verduras", qty: "1" },
      { name: "Queso", category: "Lácteos", qty: "100g" },
      { name: "Aceite de oliva", category: "Almacén", qty: "2 cdas" },
    ],
    steps: {
      es: [
        "Cortá el pollo en cubos y condimentá con sal y especias.",
        "Grillá el pollo 6-8 minutos hasta que esté cocido.",
        "Cortá el tomate y la cebolla en trozos.",
        "Armá el bowl con la base que prefieras, el pollo y los vegetales.",
        "Terminá con queso y un chorro de aceite de oliva.",
      ],
      en: [
        "Cut the chicken into cubes and season with salt and spices.",
        "Grill the chicken 6-8 minutes until cooked through.",
        "Chop the tomato and onion.",
        "Build the bowl with your base of choice, the chicken and vegetables.",
        "Finish with cheese and a drizzle of olive oil.",
      ],
    },
    tips: {
      es: ["Preparalo el doble y usalo de almuerzo al día siguiente.", "El limón exprimido arriba le da un toque fresco."],
      en: ["Double the batch and use it for lunch tomorrow.", "A squeeze of lemon on top adds a fresh touch."],
    },
    healthBenefits: {
      es: ["Rica en proteína magra y grasas saludables gracias al aceite de oliva.", "El tomate aporta licopeno y vitamina C, buenos antioxidantes."],
      en: ["Rich in lean protein and healthy fats from the olive oil.", "Tomato adds lycopene and vitamin C, both good antioxidants."],
    },
    pairing: {
      es: { side: "Hummus con pan pita.", dessert: "Yogur con miel y nueces.", drink: "Vino blanco fresco o, sin alcohol, limonada con menta." },
      en: { side: "Hummus with pita bread.", dessert: "Yogurt with honey and walnuts.", drink: "A crisp white wine, or mint lemonade if you skip alcohol." },
    },
  },
  {
    id: "veggie-pasta",
    category: "main",
    name: { es: "Pasta con vegetales de estación", en: "Seasonal vegetable pasta" },
    description: { es: "Pasta simple con vegetales salteados y un toque de queso.", en: "Simple pasta with sautéed vegetables and a touch of cheese." },
    emoji: "🍝",
    timeMinutes: 20,
    difficulty: "Easy",
    baseServings: 3,
    baseCostUSD: 6,
    baseCalories: 540,
    protein: "veg",
    cuisine: "italian",
    dietTags: ["vegetarian"],
    goalTags: ["fast", "cheap", "useWhatIHave"],
    ingredients: [
      { name: "Fideos", category: "Pastas", qty: "300g" },
      { name: "Tomate", category: "Verduras", qty: "3" },
      { name: "Zapallito", category: "Verduras", qty: "1" },
      { name: "Queso", category: "Lácteos", qty: "80g" },
      { name: "Aceite de oliva", category: "Almacén", qty: "2 cdas" },
    ],
    steps: {
      es: [
        "Herví la pasta en agua con sal según el paquete.",
        "Mientras tanto, saltea los vegetales en aceite de oliva.",
        "Mezclá los vegetales con la pasta escurrida.",
        "Terminá con queso rallado por encima.",
      ],
      en: [
        "Boil the pasta in salted water per package instructions.",
        "Meanwhile, sauté the vegetables in olive oil.",
        "Toss the vegetables with the drained pasta.",
        "Finish with grated cheese on top.",
      ],
    },
    tips: {
      es: ["Guardá un poco del agua de cocción, ayuda a que la salsa se integre.", "Cualquier vegetal que tengas a mano sirve acá."],
      en: ["Save a splash of pasta water — it helps everything come together.", "Any vegetable you have on hand works here."],
    },
    healthBenefits: {
      es: ["Los vegetales de estación suman fibra, vitamina C y antioxidantes.", "El queso aporta calcio y proteína extra."],
      en: ["Seasonal vegetables add fiber, vitamin C and antioxidants.", "Cheese adds calcium and extra protein."],
    },
    pairing: {
      es: { side: "Ensalada verde con vinagreta.", dessert: "Fruta fresca de estación.", drink: "Vino blanco liviano o agua saborizada con frutos rojos." },
      en: { side: "Green salad with vinaigrette.", dessert: "Fresh seasonal fruit.", drink: "A light white wine, or berry-infused water." },
    },
  },
  {
    id: "beef-tacos",
    category: "main",
    name: { es: "Tacos de carne", en: "Beef tacos" },
    description: { es: "Tacos rápidos con carne salteada, especiado y fresco.", en: "Quick tacos with seasoned beef, spiced and fresh." },
    emoji: "🌮",
    timeMinutes: 20,
    difficulty: "Easy",
    baseServings: 3,
    baseCostUSD: 9,
    baseCalories: 560,
    protein: "beef",
    cuisine: "mexican",
    dietTags: ["kidFriendly"],
    goalTags: ["fast", "protein"],
    ingredients: [
      { name: "Carne picada", category: "Carnes", qty: "400g" },
      { name: "Cebolla", category: "Verduras", qty: "1" },
      { name: "Tomate", category: "Verduras", qty: "2" },
      { name: "Queso", category: "Lácteos", qty: "100g" },
      { name: "Tortillas", category: "Almacén", qty: "8" },
    ],
    steps: {
      es: [
        "Saltea la carne picada con cebolla hasta dorar.",
        "Condimentá con sal, comino y pimentón.",
        "Calentá las tortillas.",
        "Armá los tacos con la carne, tomate y queso.",
      ],
      en: [
        "Sauté the ground beef with onion until browned.",
        "Season with salt, cumin and paprika.",
        "Warm the tortillas.",
        "Build the tacos with the beef, tomato and cheese.",
      ],
    },
    tips: {
      es: ["Un chorrito de lima al final le cambia todo.", "A los chicos les gusta armar los suyos."],
      en: ["A squeeze of lime at the end changes everything.", "Kids love building their own."],
    },
    healthBenefits: {
      es: ["La carne aporta hierro y proteína de alto valor biológico.", "Es una opción rica y satisfactoria — date el gusto, pero no la repitas todos los días."],
      en: ["Beef provides iron and high-quality protein.", "A satisfying, flavorful option — enjoy it, but not an everyday staple."],
    },
    pairing: {
      es: { side: "Guacamole y pico de gallo.", dessert: "Flan o fruta con crema.", drink: "Una cerveza clara o, sin alcohol, agua de jamaica bien fría." },
      en: { side: "Guacamole and pico de gallo.", dessert: "Flan or fruit with cream.", drink: "A light beer, or chilled hibiscus water if you skip alcohol." },
    },
  },
  {
    id: "salmon-veggies",
    category: "main",
    name: { es: "Salmón al horno con vegetales", en: "Baked salmon with vegetables" },
    description: { es: "Salmón horneado, liviano y lleno de proteína, con vegetales asados.", en: "Baked salmon, light and high in protein, with roasted vegetables." },
    emoji: "🐟",
    timeMinutes: 30,
    difficulty: "Medium",
    baseServings: 2,
    baseCostUSD: 14,
    baseCalories: 460,
    protein: "fish",
    cuisine: "mediterranean",
    dietTags: ["glutenFree", "dairyFree", "highProtein", "light", "lowCarb"],
    goalTags: ["healthy", "protein", "lowCalorie"],
    ingredients: [
      { name: "Pescado", category: "Carnes", qty: "2 filetes" },
      { name: "Zapallito", category: "Verduras", qty: "1" },
      { name: "Tomate", category: "Verduras", qty: "2" },
      { name: "Aceite de oliva", category: "Almacén", qty: "2 cdas" },
    ],
    steps: {
      es: [
        "Precalentá el horno a 200°C.",
        "Colocá el pescado y los vegetales cortados en una fuente.",
        "Condimentá con sal, limón y aceite de oliva.",
        "Horneá 18-20 minutos hasta que el pescado esté cocido.",
      ],
      en: [
        "Preheat the oven to 200°C / 400°F.",
        "Place the fish and chopped vegetables on a tray.",
        "Season with salt, lemon and olive oil.",
        "Bake 18-20 minutes until the fish is cooked through.",
      ],
    },
    tips: {
      es: ["No te pases de cocción: el pescado sigue cocinándose fuera del horno.", "El limón fresco es clave acá."],
      en: ["Don't overcook it — fish keeps cooking after it leaves the oven.", "Fresh lemon is key here."],
    },
    healthBenefits: {
      es: ["El pescado aporta Omega-3, muy bueno para el corazón y el cerebro.", "Bajo en carbohidratos y rico en proteína magra."],
      en: ["Fish provides Omega-3s, great for heart and brain health.", "Low in carbs and rich in lean protein."],
    },
    pairing: {
      es: { side: "Puré de coliflor o quinoa.", dessert: "Ensalada de frutas cítricas.", drink: "Un vino blanco (Chardonnay) o agua con pepino y menta." },
      en: { side: "Cauliflower mash or quinoa.", dessert: "Citrus fruit salad.", drink: "A white wine (Chardonnay), or cucumber-mint water." },
    },
  },
  {
    id: "lentil-soup",
    category: "main",
    name: { es: "Guiso de lentejas", en: "Lentil stew" },
    description: { es: "Un guiso abundante, económico y reconfortante.", en: "A hearty, budget-friendly and comforting stew." },
    emoji: "🍲",
    timeMinutes: 40,
    difficulty: "Easy",
    baseServings: 4,
    baseCostUSD: 5,
    baseCalories: 420,
    protein: "legume",
    cuisine: "comfort",
    dietTags: ["vegan", "dairyFree", "lowSodium"],
    goalTags: ["cheap", "healthy", "useWhatIHave"],
    ingredients: [
      { name: "Lentejas", category: "Almacén", qty: "300g" },
      { name: "Cebolla", category: "Verduras", qty: "1" },
      { name: "Tomate", category: "Verduras", qty: "2" },
      { name: "Papa", category: "Verduras", qty: "2" },
    ],
    steps: {
      es: [
        "Rehogá la cebolla hasta que esté transparente.",
        "Agregá el tomate picado y cociná 3 minutos.",
        "Sumá las lentejas, la papa en cubos y agua.",
        "Cociná a fuego medio 25-30 minutos hasta espesar.",
      ],
      en: [
        "Sauté the onion until translucent.",
        "Add the chopped tomato and cook 3 minutes.",
        "Add the lentils, diced potato and water.",
        "Simmer 25-30 minutes until thickened.",
      ],
    },
    tips: {
      es: ["Rinde para varios días y mejora al día siguiente.", "Congelá porciones individuales."],
      en: ["It makes plenty and tastes even better the next day.", "Freeze it in individual portions."],
    },
    healthBenefits: {
      es: ["Las lentejas son ricas en hierro, fibra y proteína vegetal.", "Ayudan a mantenerte saciada por más tiempo."],
      en: ["Lentils are rich in iron, fiber and plant protein.", "They help keep you full for longer."],
    },
    pairing: {
      es: { side: "Pan casero o tostadas.", dessert: "Manzana asada con canela.", drink: "Un vino tinto liviano o té de jengibre." },
      en: { side: "Homemade bread or toast.", dessert: "Baked apple with cinnamon.", drink: "A light red wine, or ginger tea." },
    },
  },
  {
    id: "egg-fried-rice",
    category: "main",
    name: { es: "Arroz frito con huevo", en: "Egg fried rice" },
    description: { es: "La forma perfecta de usar arroz que te sobró.", en: "The perfect way to use leftover rice." },
    emoji: "🍳",
    timeMinutes: 15,
    difficulty: "Easy",
    baseServings: 2,
    baseCostUSD: 4,
    baseCalories: 430,
    protein: "egg",
    cuisine: "asian",
    dietTags: ["vegetarian", "dairyFree"],
    goalTags: ["fast", "cheap", "useWhatIHave", "easy"],
    ingredients: [
      { name: "Arroz", category: "Almacén", qty: "2 tazas (cocido)" },
      { name: "Huevos", category: "Huevos", qty: "3" },
      { name: "Cebolla", category: "Verduras", qty: "1" },
      { name: "Salsa de soja", category: "Almacén", qty: "2 cdas" },
    ],
    steps: {
      es: [
        "Batí los huevos y cociná una tortilla suave, reservá.",
        "Saltea la cebolla en un poco de aceite.",
        "Agregá el arroz y saltea a fuego fuerte 3-4 minutos.",
        "Sumá el huevo cortado en trozos y la salsa de soja.",
      ],
      en: [
        "Beat the eggs and cook a soft omelet, set aside.",
        "Sauté the onion in a bit of oil.",
        "Add the rice and stir-fry on high heat 3-4 minutes.",
        "Add the chopped egg and soy sauce.",
      ],
    },
    tips: {
      es: ["Arroz frío del día anterior queda mejor que recién hecho.", "Sumá cualquier verdura que tengas guardada."],
      en: ["Day-old cold rice works better than fresh.", "Toss in any vegetable scraps you have."],
    },
    healthBenefits: {
      es: ["El huevo aporta proteína completa y vitamina D.", "Es ideal para aprovechar sobras rápido — perfecta de vez en cuando, no pensada para el día a día."],
      en: ["Eggs provide complete protein and vitamin D.", "A great way to use up leftovers fast — perfect once in a while, not an everyday staple."],
    },
    pairing: {
      es: { side: "Ensalada de pepino y zanahoria.", dessert: "Fruta fresca, para equilibrar.", drink: "Té verde o agua con limón." },
      en: { side: "Cucumber and carrot salad.", dessert: "Fresh fruit, to balance the meal.", drink: "Green tea or lemon water." },
    },
  },
  {
    id: "chickpea-curry",
    category: "main",
    name: { es: "Curry de garbanzos", en: "Chickpea curry" },
    description: { es: "Curry cremoso, especiado y 100% vegetal.", en: "Creamy, spiced, fully plant-based curry." },
    emoji: "🍛",
    timeMinutes: 30,
    difficulty: "Easy",
    baseServings: 3,
    baseCostUSD: 6,
    baseCalories: 470,
    protein: "legume",
    cuisine: "asian",
    dietTags: ["vegan", "dairyFree", "glutenFree"],
    goalTags: ["cheap", "healthy"],
    ingredients: [
      { name: "Garbanzos", category: "Almacén", qty: "400g" },
      { name: "Cebolla", category: "Verduras", qty: "1" },
      { name: "Tomate", category: "Verduras", qty: "2" },
      { name: "Especias", category: "Especias", qty: "curry, comino" },
    ],
    steps: {
      es: [
        "Rehogá la cebolla con las especias hasta que perfume.",
        "Agregá el tomate y cociná 5 minutos.",
        "Sumá los garbanzos y un poco de agua.",
        "Cociná a fuego bajo 15 minutos.",
      ],
      en: [
        "Sauté the onion with the spices until fragrant.",
        "Add the tomato and cook 5 minutes.",
        "Add the chickpeas and a splash of water.",
        "Simmer on low heat 15 minutes.",
      ],
    },
    tips: {
      es: ["Si tenés leche de coco, sumala para una versión más cremosa.", "Acompañá con arroz o pan plano."],
      en: ["If you have coconut milk, add it for a creamier version.", "Serve with rice or flatbread."],
    },
    healthBenefits: {
      es: ["Los garbanzos aportan proteína vegetal, fibra y hierro.", "Su fibra ayuda a mantener el azúcar en sangre más estable."],
      en: ["Chickpeas provide plant protein, fiber and iron.", "Their fiber helps keep blood sugar more stable."],
    },
    pairing: {
      es: { side: "Arroz basmati o pan naan.", dessert: "Yogur con miel.", drink: "Té chai o jugo de mango." },
      en: { side: "Basmati rice or naan bread.", dessert: "Yogurt with honey.", drink: "Chai tea or mango juice." },
    },
  },
  {
    id: "turkey-meatballs",
    category: "main",
    name: { es: "Albóndigas al horno", en: "Baked meatballs" },
    description: { es: "Albóndigas jugosas, apto para chicos y fáciles de congelar.", en: "Juicy meatballs, kid-friendly and easy to freeze." },
    emoji: "🍖",
    timeMinutes: 35,
    difficulty: "Medium",
    baseServings: 4,
    baseCostUSD: 10,
    baseCalories: 500,
    protein: "beef",
    cuisine: "comfort",
    dietTags: ["kidFriendly", "highProtein"],
    goalTags: ["protein", "healthy"],
    ingredients: [
      { name: "Carne picada", category: "Carnes", qty: "500g" },
      { name: "Huevos", category: "Huevos", qty: "1" },
      { name: "Cebolla", category: "Verduras", qty: "1" },
      { name: "Tomate", category: "Verduras", qty: "2" },
    ],
    steps: {
      es: [
        "Mezclá la carne con huevo, cebolla rallada y sal.",
        "Formá bolitas parejas.",
        "Horneá 20 minutos a 200°C.",
        "Napá con salsa de tomate casera los últimos 5 minutos.",
      ],
      en: [
        "Mix the beef with egg, grated onion and salt.",
        "Shape into even balls.",
        "Bake 20 minutes at 200°C / 400°F.",
        "Coat with homemade tomato sauce for the last 5 minutes.",
      ],
    },
    tips: {
      es: ["Hacé el doble y congelá crudas para otro día.", "Servilas con puré para que sea más apto para chicos."],
      en: ["Double the batch and freeze raw ones for later.", "Serve with mashed potatoes to make it extra kid-friendly."],
    },
    healthBenefits: {
      es: ["Alta en proteína, ideal para el crecimiento de los chicos.", "Horneadas en vez de fritas: bastante menos grasa que la versión tradicional."],
      en: ["High in protein, great for kids' growth.", "Baked instead of fried — noticeably less fat than the traditional version."],
    },
    pairing: {
      es: { side: "Puré de papas o ensalada verde.", dessert: "Gelatina de frutas.", drink: "Vino tinto liviano o jugo de uva." },
      en: { side: "Mashed potatoes or green salad.", dessert: "Fruit gelatin.", drink: "A light red wine, or grape juice." },
    },
  },
  {
    id: "greek-salad-chicken",
    category: "main",
    name: { es: "Ensalada griega con pollo", en: "Greek salad with chicken" },
    description: { es: "Fresca, liviana y lista en minutos.", en: "Fresh, light and ready in minutes." },
    emoji: "🥙",
    timeMinutes: 15,
    difficulty: "Easy",
    baseServings: 2,
    baseCostUSD: 9,
    baseCalories: 380,
    protein: "chicken",
    cuisine: "mediterranean",
    dietTags: ["glutenFree", "lowCarb", "light", "highProtein"],
    goalTags: ["fast", "lowCalorie", "healthy"],
    ingredients: [
      { name: "Pollo", category: "Carnes", qty: "300g" },
      { name: "Tomate", category: "Verduras", qty: "2" },
      { name: "Cebolla", category: "Verduras", qty: "1/2" },
      { name: "Queso", category: "Lácteos", qty: "100g" },
      { name: "Aceite de oliva", category: "Almacén", qty: "2 cdas" },
    ],
    steps: {
      es: [
        "Grillá el pollo condimentado 6 minutos de cada lado.",
        "Cortá tomate y cebolla en trozos.",
        "Mezclá los vegetales con aceite de oliva y sal.",
        "Sumá el pollo en fetas y el queso encima.",
      ],
      en: [
        "Grill the seasoned chicken 6 minutes per side.",
        "Chop the tomato and onion.",
        "Toss the vegetables with olive oil and salt.",
        "Top with sliced chicken and cheese.",
      ],
    },
    tips: {
      es: ["Perfecta para calor: liviana y refrescante.", "Podés preparar el pollo de más para el día siguiente."],
      en: ["Perfect for hot days: light and refreshing.", "Grill extra chicken for tomorrow's lunch."],
    },
    healthBenefits: {
      es: ["Fresca y liviana: aporta proteína magra y grasas saludables del aceite de oliva.", "El tomate y la cebolla suman antioxidantes."],
      en: ["Fresh and light: lean protein plus healthy fats from the olive oil.", "Tomato and onion add antioxidants."],
    },
    pairing: {
      es: { side: "Pan pita tostado.", dessert: "Yogur griego con miel.", drink: "Vino blanco fresco o limonada." },
      en: { side: "Toasted pita bread.", dessert: "Greek yogurt with honey.", drink: "A crisp white wine, or lemonade." },
    },
  },
  {
    id: "tofu-veggie-stirfry",
    category: "main",
    name: { es: "Salteado de tofu y vegetales", en: "Tofu and vegetable stir fry" },
    description: { es: "Salteado rápido, 100% vegetal y lleno de textura.", en: "Quick stir fry, fully plant-based and full of texture." },
    emoji: "🥦",
    timeMinutes: 20,
    difficulty: "Easy",
    baseServings: 2,
    baseCostUSD: 6,
    baseCalories: 400,
    protein: "tofu",
    cuisine: "asian",
    dietTags: ["vegan", "dairyFree", "glutenFree"],
    goalTags: ["healthy", "fast"],
    ingredients: [
      { name: "Zapallito", category: "Verduras", qty: "1" },
      { name: "Cebolla", category: "Verduras", qty: "1" },
      { name: "Salsa de soja", category: "Almacén", qty: "2 cdas" },
      { name: "Arroz", category: "Almacén", qty: "1 taza" },
    ],
    steps: {
      es: [
        "Cortá el tofu en cubos y dóralo en la sartén.",
        "Retirá y saltea la cebolla y el zapallito.",
        "Volvé a sumar el tofu junto con la salsa de soja.",
        "Serví sobre arroz.",
      ],
      en: [
        "Cube the tofu and pan-fry until golden.",
        "Set aside and stir-fry the onion and zucchini.",
        "Return the tofu with the soy sauce.",
        "Serve over rice.",
      ],
    },
    tips: {
      es: ["Secá bien el tofu antes de dorarlo para que quede crocante.", "Fuego fuerte, movimiento constante."],
      en: ["Pat the tofu dry before frying for a crispier bite.", "High heat, constant movement."],
    },
    healthBenefits: {
      es: ["El tofu aporta proteína vegetal completa y calcio.", "100% vegetal y bajo en grasas saturadas."],
      en: ["Tofu provides complete plant protein and calcium.", "Fully plant-based and low in saturated fat."],
    },
    pairing: {
      es: { side: "Arroz integral.", dessert: "Fruta fresca.", drink: "Té verde o agua de coco." },
      en: { side: "Brown rice.", dessert: "Fresh fruit.", drink: "Green tea or coconut water." },
    },
  },
  {
    id: "baked-chicken-thighs",
    category: "main",
    name: { es: "Muslos de pollo al horno con papas", en: "Baked chicken thighs with potatoes" },
    description: { es: "Comfort food clásico, todo en una sola fuente.", en: "Classic comfort food, all on one tray." },
    emoji: "🍗",
    timeMinutes: 45,
    difficulty: "Easy",
    baseServings: 4,
    baseCostUSD: 11,
    baseCalories: 610,
    protein: "chicken",
    cuisine: "comfort",
    dietTags: ["glutenFree", "dairyFree"],
    goalTags: ["easy", "useWhatIHave"],
    ingredients: [
      { name: "Pollo", category: "Carnes", qty: "800g (muslos)" },
      { name: "Papa", category: "Verduras", qty: "4" },
      { name: "Cebolla", category: "Verduras", qty: "1" },
      { name: "Aceite de oliva", category: "Almacén", qty: "2 cdas" },
    ],
    steps: {
      es: [
        "Precalentá el horno a 200°C.",
        "Colocá el pollo y las papas en trozos en una fuente.",
        "Condimentá con sal, especias y aceite de oliva.",
        "Horneá 40 minutos hasta que estén dorados.",
      ],
      en: [
        "Preheat the oven to 200°C / 400°F.",
        "Place the chicken and cut potatoes on a tray.",
        "Season with salt, spices and olive oil.",
        "Bake 40 minutes until golden.",
      ],
    },
    tips: {
      es: ["Una sola fuente, casi nada para lavar.", "Sobra para el almuerzo de mañana."],
      en: ["One tray, almost nothing to wash.", "Leftovers make a great lunch tomorrow."],
    },
    healthBenefits: {
      es: ["El pollo aporta proteína magra; horneado en vez de frito.", "La papa suma potasio y energía de buena calidad."],
      en: ["Chicken provides lean protein; baked instead of fried.", "Potatoes add potassium and good-quality energy."],
    },
    pairing: {
      es: { side: "Ensalada verde.", dessert: "Compota de manzana.", drink: "Vino tinto liviano o jugo de arándanos." },
      en: { side: "Green salad.", dessert: "Apple compote.", drink: "A light red wine, or cranberry juice." },
    },
  },
  {
    id: "quesadillas",
    category: "main",
    name: { es: "Quesadillas", en: "Quesadillas" },
    description: { es: "Rápidas, apto para chicos, ideales cuando el tiempo apremia.", en: "Fast, kid-friendly, perfect when time is tight." },
    emoji: "🧀",
    timeMinutes: 15,
    difficulty: "Easy",
    baseServings: 2,
    baseCostUSD: 5,
    baseCalories: 450,
    protein: "veg",
    cuisine: "mexican",
    dietTags: ["vegetarian", "kidFriendly"],
    goalTags: ["fast", "easy", "cheap"],
    ingredients: [
      { name: "Tortillas", category: "Almacén", qty: "4" },
      { name: "Queso", category: "Lácteos", qty: "200g" },
      { name: "Cebolla", category: "Verduras", qty: "1/2" },
    ],
    steps: {
      es: [
        "Rellená las tortillas con queso y cebolla picada.",
        "Cociná en sartén 2-3 minutos de cada lado.",
        "Cortá en triángulos y serví caliente.",
      ],
      en: [
        "Fill the tortillas with cheese and chopped onion.",
        "Cook in a pan 2-3 minutes per side.",
        "Cut into triangles and serve hot.",
      ],
    },
    tips: {
      es: ["Sumá pollo si tenés de sobra.", "Acompañá con algo fresco al costado."],
      en: ["Add leftover chicken if you have some.", "Serve with something fresh on the side."],
    },
    healthBenefits: {
      es: ["El queso aporta calcio y proteína.", "Es rápida y rica — mejor acompañada de algo fresco, no pensada para comer todos los días."],
      en: ["Cheese adds calcium and protein.", "Quick and tasty — best paired with something fresh, not an everyday choice."],
    },
    pairing: {
      es: { side: "Guacamole y pico de gallo.", dessert: "Fruta fresca, para equilibrar.", drink: "Agua de jamaica o limonada." },
      en: { side: "Guacamole and pico de gallo.", dessert: "Fresh fruit, to balance the meal.", drink: "Hibiscus water or lemonade." },
    },
  },
  {
    id: "shakshuka",
    category: "main",
    name: { es: "Shakshuka", en: "Shakshuka" },
    description: { es: "Huevos pochados en salsa de tomate especiada. Comfort food vegetariano.", en: "Poached eggs in spiced tomato sauce. Vegetarian comfort food." },
    emoji: "🍅",
    timeMinutes: 25,
    difficulty: "Easy",
    baseServings: 2,
    baseCostUSD: 6,
    baseCalories: 410,
    protein: "egg",
    cuisine: "comfort",
    dietTags: ["vegetarian", "glutenFree"],
    goalTags: ["cheap", "useWhatIHave"],
    ingredients: [
      { name: "Huevos", category: "Huevos", qty: "4" },
      { name: "Tomate", category: "Verduras", qty: "4" },
      { name: "Cebolla", category: "Verduras", qty: "1" },
      { name: "Especias", category: "Especias", qty: "pimentón, comino" },
    ],
    steps: {
      es: [
        "Rehogá la cebolla con las especias.",
        "Agregá el tomate y cociná 10 minutos hasta espesar.",
        "Hacé espacios y cascá los huevos encima.",
        "Tapá y cociná hasta que la clara esté firme.",
      ],
      en: [
        "Sauté the onion with the spices.",
        "Add the tomato and simmer 10 minutes until thickened.",
        "Make wells and crack the eggs on top.",
        "Cover and cook until the whites are set.",
      ],
    },
    tips: {
      es: ["Serví con pan para mojar en la salsa.", "La yema tiene que quedar líquida."],
      en: ["Serve with bread for dipping.", "The yolk should stay runny."],
    },
    healthBenefits: {
      es: ["Los huevos aportan proteína completa y vitamina D.", "El tomate cocido potencia el licopeno, un antioxidante fuerte."],
      en: ["Eggs provide complete protein and vitamin D.", "Cooked tomato boosts lycopene, a powerful antioxidant."],
    },
    pairing: {
      es: { side: "Pan árabe o tostadas.", dessert: "Fruta fresca.", drink: "Té de menta o jugo de naranja." },
      en: { side: "Flatbread or toast.", dessert: "Fresh fruit.", drink: "Mint tea or orange juice." },
    },
  },
  {
    id: "beef-rice-bowl",
    category: "main",
    name: { es: "Bowl de carne y arroz", en: "Beef and rice bowl" },
    description: { es: "Un bowl abundante, rico en proteína y fácil de armar.", en: "A hearty, high-protein bowl that's easy to put together." },
    emoji: "🍚",
    timeMinutes: 30,
    difficulty: "Easy",
    baseServings: 3,
    baseCostUSD: 10,
    baseCalories: 590,
    protein: "beef",
    cuisine: "asian",
    dietTags: ["dairyFree", "highProtein"],
    goalTags: ["protein", "easy"],
    ingredients: [
      { name: "Carne picada", category: "Carnes", qty: "400g" },
      { name: "Arroz", category: "Almacén", qty: "1.5 tazas" },
      { name: "Cebolla", category: "Verduras", qty: "1" },
      { name: "Salsa de soja", category: "Almacén", qty: "2 cdas" },
    ],
    steps: {
      es: [
        "Cociná el arroz según el paquete.",
        "Saltea la carne con cebolla hasta dorar.",
        "Condimentá con salsa de soja.",
        "Armá el bowl con arroz y la carne encima.",
      ],
      en: [
        "Cook the rice according to the package.",
        "Sauté the beef with onion until browned.",
        "Season with soy sauce.",
        "Build the bowl with rice topped with the beef.",
      ],
    },
    tips: {
      es: ["Un huevo frito arriba lo lleva a otro nivel.", "Sumá cualquier vegetal salteado que tengas."],
      en: ["A fried egg on top takes it to another level.", "Add any sautéed vegetable you have."],
    },
    healthBenefits: {
      es: ["La carne aporta hierro y proteína de alto valor biológico.", "Sumale vegetales salteados al costado para agregar fibra y vitaminas."],
      en: ["Beef provides iron and high-quality protein.", "Add sautéed vegetables on the side for extra fiber and vitamins."],
    },
    pairing: {
      es: { side: "Vegetales salteados.", dessert: "Fruta fresca.", drink: "Una cerveza o té helado." },
      en: { side: "Sautéed vegetables.", dessert: "Fresh fruit.", drink: "A beer, or iced tea." },
    },
  },
  {
    id: "shrimp-zoodles",
    category: "main",
    name: { es: "Fideos de zapallito con camarones", en: "Zucchini noodles with shrimp" },
    description: { es: "Liviano, bajo en carbohidratos y listo en minutos.", en: "Light, low-carb and ready in minutes." },
    emoji: "🍤",
    timeMinutes: 20,
    difficulty: "Medium",
    baseServings: 2,
    baseCostUSD: 13,
    baseCalories: 350,
    protein: "fish",
    cuisine: "mediterranean",
    dietTags: ["glutenFree", "dairyFree", "lowCarb", "light", "highProtein"],
    goalTags: ["healthy", "lowCalorie", "fast"],
    ingredients: [
      { name: "Zapallito", category: "Verduras", qty: "3" },
      { name: "Tomate", category: "Verduras", qty: "2" },
      { name: "Aceite de oliva", category: "Almacén", qty: "2 cdas" },
    ],
    steps: {
      es: [
        "Cortá el zapallito en tiras finas tipo fideos.",
        "Saltea los camarones 2-3 minutos por lado.",
        "Sumá el tomate y el zapallito, cociná 3 minutos más.",
        "Condimentá y serví enseguida.",
      ],
      en: [
        "Cut the zucchini into thin noodle-like strips.",
        "Sauté the shrimp 2-3 minutes per side.",
        "Add the tomato and zucchini, cook 3 more minutes.",
        "Season and serve right away.",
      ],
    },
    tips: {
      es: ["No lo cocines de más, el zapallito suelta agua rápido.", "Servilo apenas esté listo."],
      en: ["Don't overcook it — zucchini releases water fast.", "Serve it right away."],
    },
    healthBenefits: {
      es: ["Los camarones son bajos en grasa y ricos en proteína y yodo.", "El zapallito en lugar de fideos reduce bastante los carbohidratos."],
      en: ["Shrimp is low in fat and rich in protein and iodine.", "Zucchini instead of pasta cuts down significantly on carbs."],
    },
    pairing: {
      es: { side: "Ensalada verde liviana.", dessert: "Sorbete de limón.", drink: "Vino blanco (Sauvignon Blanc) o agua con pepino." },
      en: { side: "Light green salad.", dessert: "Lemon sorbet.", drink: "A white wine (Sauvignon Blanc), or cucumber water." },
    },
  },
  {
    id: "pumpkin-soup",
    category: "main",
    name: { es: "Sopa de calabaza", en: "Pumpkin soup" },
    description: { es: "Cremosa, liviana y perfecta para un día frío.", en: "Creamy, light and perfect for a cold day." },
    emoji: "🎃",
    timeMinutes: 30,
    difficulty: "Easy",
    baseServings: 4,
    baseCostUSD: 6,
    baseCalories: 320,
    protein: "veg",
    cuisine: "comfort",
    dietTags: ["vegan", "dairyFree", "glutenFree", "light"],
    goalTags: ["healthy", "lowCalorie", "cheap"],
    ingredients: [
      { name: "Zapallo", category: "Verduras", qty: "800g" },
      { name: "Cebolla", category: "Verduras", qty: "1" },
      { name: "Papa", category: "Verduras", qty: "1" },
    ],
    steps: {
      es: [
        "Rehogá la cebolla hasta transparentar.",
        "Sumá el zapallo y la papa en cubos.",
        "Cubrí con agua y cociná 20 minutos.",
        "Licuá hasta lograr una crema suave.",
      ],
      en: [
        "Sauté the onion until translucent.",
        "Add the cubed pumpkin and potato.",
        "Cover with water and cook 20 minutes.",
        "Blend until smooth and creamy.",
      ],
    },
    tips: {
      es: ["Un toque de jengibre le da vida.", "Se congela perfecto en porciones."],
      en: ["A touch of ginger brings it to life.", "Freezes perfectly in portions."],
    },
    healthBenefits: {
      es: ["El zapallo aporta beta-caroteno, bueno para la vista y las defensas.", "Liviana y baja en calorías, ideal para la noche."],
      en: ["Pumpkin provides beta-carotene, great for eyesight and immunity.", "Light and low-calorie, perfect for dinner."],
    },
    pairing: {
      es: { side: "Pan crocante.", dessert: "Peras al horno con canela.", drink: "Vino blanco o té de jengibre." },
      en: { side: "Crusty bread.", dessert: "Baked pears with cinnamon.", drink: "A white wine, or ginger tea." },
    },
  },
  {
    id: "chicken-caesar-wrap",
    category: "main",
    name: { es: "Wrap césar de pollo", en: "Chicken Caesar wrap" },
    description: { es: "Rápido, fresco y para llevar a cualquier lado.", en: "Fast, fresh, and easy to take anywhere." },
    emoji: "🌯",
    timeMinutes: 15,
    difficulty: "Easy",
    baseServings: 2,
    baseCostUSD: 8,
    baseCalories: 480,
    protein: "chicken",
    cuisine: "fresh",
    dietTags: ["highProtein"],
    goalTags: ["fast", "protein", "easy"],
    ingredients: [
      { name: "Pollo", category: "Carnes", qty: "300g" },
      { name: "Queso", category: "Lácteos", qty: "60g" },
      { name: "Tortillas", category: "Almacén", qty: "2" },
    ],
    steps: {
      es: [
        "Grillá o usá pollo cocido y cortalo en tiras.",
        "Calentá las tortillas.",
        "Armá el wrap con pollo, queso y aderezo a gusto.",
        "Enrollá bien apretado y cortá al medio.",
      ],
      en: [
        "Grill or use cooked chicken, cut into strips.",
        "Warm the tortillas.",
        "Build the wrap with chicken, cheese and dressing to taste.",
        "Roll tightly and cut in half.",
      ],
    },
    tips: {
      es: ["Perfecto para usar pollo que sobró.", "Envolvelo en papel para que no se abra."],
      en: ["Perfect for using leftover chicken.", "Wrap it in paper so it holds together."],
    },
    healthBenefits: {
      es: ["Buena fuente de proteína magra para reponer energía.", "Elegí una tortilla integral si podés, para sumar más fibra."],
      en: ["A good source of lean protein to refuel.", "Choose a whole-wheat wrap if you can, for extra fiber."],
    },
    pairing: {
      es: { side: "Bastones de zanahoria y apio.", dessert: "Fruta fresca.", drink: "Limonada o agua saborizada." },
      en: { side: "Carrot and celery sticks.", dessert: "Fresh fruit.", drink: "Lemonade or infused water." },
    },
  },
  {
    id: "yogurt-granola-berries",
    category: "snack",
    name: { es: "Yogur con granola y frutos rojos", en: "Yogurt with granola and berries" },
    description: { es: "Cremoso, dulce y listo en un minuto.", en: "Creamy, sweet and ready in a minute." },
    emoji: "🍓",
    timeMinutes: 3,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 2,
    baseCalories: 220,
    protein: "veg",
    cuisine: "fresh",
    dietTags: ["vegetarian", "highProtein"],
    goalTags: ["fast", "healthy", "easy"],
    ingredients: [
      { name: "Yogur natural", category: "Lácteos", qty: "1 pote" },
      { name: "Granola", category: "Almacén", qty: "3 cdas" },
      { name: "Frutos rojos", category: "Frutas", qty: "1 puñado" },
    ],
    steps: {
      es: ["Serví el yogur en un bowl.", "Agregá la granola y los frutos rojos arriba."],
      en: ["Serve the yogurt in a bowl.", "Add the granola and berries on top."],
    },
    tips: {
      es: ["Si no tenés frutos rojos, cualquier fruta picada sirve."],
      en: ["No berries? Any chopped fruit works."],
    },
    healthBenefits: {
      es: ["El yogur aporta calcio y probióticos buenos para la digestión.", "Los frutos rojos suman antioxidantes."],
      en: ["Yogurt provides calcium and probiotics that help digestion.", "Berries add antioxidants."],
    },
    pairing: {
      es: { side: "Un puñado de nueces.", dessert: "Ya es un snack dulce, no necesita más.", drink: "Agua o té helado sin azúcar." },
      en: { side: "A handful of walnuts.", dessert: "It's already a sweet snack — no dessert needed.", drink: "Water or unsweetened iced tea." },
    },
  },
  {
    id: "carrot-celery-hummus",
    category: "snack",
    name: { es: "Bastones de zanahoria y apio con hummus", en: "Carrot and celery sticks with hummus" },
    description: { es: "Crocante, fresco y fácil de llevar.", en: "Crunchy, fresh and easy to take with you." },
    emoji: "🥕",
    timeMinutes: 5,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 2,
    baseCalories: 150,
    protein: "veg",
    cuisine: "fresh",
    dietTags: ["vegan", "glutenFree"],
    goalTags: ["healthy", "fast", "cheap"],
    ingredients: [
      { name: "Zanahoria", category: "Verduras", qty: "1" },
      { name: "Apio", category: "Verduras", qty: "2 ramas" },
      { name: "Hummus", category: "Almacén", qty: "3 cdas" },
    ],
    steps: {
      es: ["Cortá la zanahoria y el apio en bastones.", "Serví con el hummus para untar."],
      en: ["Cut the carrot and celery into sticks.", "Serve with hummus for dipping."],
    },
    tips: {
      es: ["Preparalos en tandas para la semana y guardalos en la heladera."],
      en: ["Prep a batch for the whole week and keep them in the fridge."],
    },
    healthBenefits: {
      es: ["La zanahoria aporta beta-caroteno, bueno para la vista.", "El hummus suma proteína vegetal y fibra."],
      en: ["Carrot provides beta-carotene, great for eyesight.", "Hummus adds plant protein and fiber."],
    },
    pairing: {
      es: { side: "Nada más, ya es completo.", dessert: "Un par de dátiles si querés algo dulce.", drink: "Agua saborizada con pepino." },
      en: { side: "Nothing else needed, it's already complete.", dessert: "A couple of dates if you want something sweet.", drink: "Cucumber-infused water." },
    },
  },
  {
    id: "avocado-toast-egg",
    category: "snack",
    name: { es: "Tostada de palta con huevo", en: "Avocado toast with egg" },
    description: { es: "El clásico que llena y da energía de verdad.", en: "The classic that actually fills you up with real energy." },
    emoji: "🥑",
    timeMinutes: 8,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 3,
    baseCalories: 280,
    protein: "egg",
    cuisine: "fresh",
    dietTags: ["vegetarian", "highProtein"],
    goalTags: ["healthy", "fast"],
    ingredients: [
      { name: "Pan integral", category: "Almacén", qty: "1 rebanada" },
      { name: "Palta", category: "Frutas", qty: "1/2" },
      { name: "Huevo", category: "Huevos", qty: "1" },
    ],
    steps: {
      es: ["Tostá el pan.", "Pisá la palta y untala encima.", "Coroná con un huevo frito o poché."],
      en: ["Toast the bread.", "Mash the avocado and spread it on top.", "Top with a fried or poached egg."],
    },
    tips: {
      es: ["Un toque de limón sobre la palta evita que se oxide."],
      en: ["A splash of lemon on the avocado keeps it from browning."],
    },
    healthBenefits: {
      es: ["La palta aporta grasas saludables (monoinsaturadas).", "El huevo suma proteína completa y vitamina D."],
      en: ["Avocado provides healthy (monounsaturated) fats.", "Egg adds complete protein and vitamin D."],
    },
    pairing: {
      es: { side: "Tomate cherry al costado.", dessert: "No hace falta postre, ya es abundante.", drink: "Café o té sin azúcar." },
      en: { side: "Cherry tomatoes on the side.", dessert: "No dessert needed, it's already filling.", drink: "Coffee or tea, no sugar." },
    },
  },
  {
    id: "nuts-dried-fruit-mix",
    category: "snack",
    name: { es: "Mix casero de frutos secos y frutas deshidratadas", en: "Homemade nut and dried fruit mix" },
    description: { es: "El snack de emergencia que siempre podés tener a mano.", en: "The emergency snack you can always have on hand." },
    emoji: "🥜",
    timeMinutes: 2,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 2,
    baseCalories: 200,
    protein: "veg",
    cuisine: "fresh",
    dietTags: ["vegan", "glutenFree", "dairyFree"],
    goalTags: ["fast", "healthy", "easy"],
    ingredients: [
      { name: "Almendras o nueces", category: "Almacén", qty: "1 puñado" },
      { name: "Pasas de uva", category: "Almacén", qty: "1 puñado" },
      { name: "Orejones", category: "Almacén", qty: "2" },
    ],
    steps: {
      es: ["Mezclá todo en un pote chico.", "Llevalo con vos para cuando te dé hambre."],
      en: ["Mix everything in a small container.", "Take it with you for when hunger strikes."],
    },
    tips: {
      es: ["Armá varias porciones el domingo para toda la semana."],
      en: ["Portion out several servings on Sunday for the whole week."],
    },
    healthBenefits: {
      es: ["Los frutos secos aportan grasas buenas y magnesio.", "Las frutas deshidratadas suman energía rápida y fibra."],
      en: ["Nuts provide good fats and magnesium.", "Dried fruit adds quick energy and fiber."],
    },
    pairing: {
      es: { side: "Nada, es un snack completo por sí solo.", dessert: "—", drink: "Agua es lo ideal, ya trae azúcares naturales." },
      en: { side: "Nothing else, it's a complete snack on its own.", dessert: "—", drink: "Water is ideal, it already has natural sugars." },
    },
  },
  {
    id: "hardboiled-eggs",
    category: "snack",
    name: { es: "Huevos duros con sal y pimienta", en: "Hard-boiled eggs with salt and pepper" },
    description: { es: "El snack con más proteína por menos esfuerzo.", en: "The highest-protein, lowest-effort snack there is." },
    emoji: "🥚",
    timeMinutes: 12,
    difficulty: "Easy",
    baseServings: 2,
    baseCostUSD: 1,
    baseCalories: 140,
    protein: "egg",
    cuisine: "fresh",
    dietTags: ["vegetarian", "glutenFree", "highProtein"],
    goalTags: ["cheap", "healthy", "easy"],
    ingredients: [
      { name: "Huevos", category: "Huevos", qty: "2" },
    ],
    steps: {
      es: ["Herví los huevos 9-10 minutos.", "Enfrialos en agua, pelalos y condimentá."],
      en: ["Boil the eggs for 9-10 minutes.", "Cool them in water, peel and season."],
    },
    tips: {
      es: ["Herví media docena juntos y guardalos en la heladera para toda la semana."],
      en: ["Boil half a dozen at once and keep them in the fridge for the week."],
    },
    healthBenefits: {
      es: ["Proteína completa y vitamina D en su forma más simple.", "Ayudan a mantenerte saciada por más tiempo."],
      en: ["Complete protein and vitamin D in their simplest form.", "They help keep you full for longer."],
    },
    pairing: {
      es: { side: "Un poco de palta pisada.", dessert: "Fruta fresca después.", drink: "Agua o mate." },
      en: { side: "A bit of mashed avocado.", dessert: "Fresh fruit afterward.", drink: "Water or herbal tea." },
    },
  },
  {
    id: "apple-peanut-butter",
    category: "snack",
    name: { es: "Manzana con manteca de maní", en: "Apple with peanut butter" },
    description: { es: "Dulce, crocante y con proteína que sostiene.", en: "Sweet, crunchy, and with protein that keeps you full." },
    emoji: "🍎",
    timeMinutes: 3,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 1,
    baseCalories: 190,
    protein: "veg",
    cuisine: "fresh",
    dietTags: ["vegetarian", "vegan", "glutenFree"],
    goalTags: ["fast", "healthy", "easy"],
    ingredients: [
      { name: "Manzana", category: "Frutas", qty: "1" },
      { name: "Manteca de maní", category: "Almacén", qty: "2 cdas" },
    ],
    steps: {
      es: ["Cortá la manzana en gajos.", "Untá o mojá cada gajo en la manteca de maní."],
      en: ["Cut the apple into wedges.", "Spread or dip each wedge in peanut butter."],
    },
    tips: {
      es: ["Elegí manteca de maní sin azúcar agregada si podés."],
      en: ["Choose peanut butter with no added sugar if you can."],
    },
    healthBenefits: {
      es: ["La manzana aporta fibra que ayuda a la digestión.", "La manteca de maní suma proteína y grasas saludables."],
      en: ["Apple provides fiber that aids digestion.", "Peanut butter adds protein and healthy fats."],
    },
    pairing: {
      es: { side: "Canela espolvoreada arriba.", dessert: "Ya es dulce, no necesita más.", drink: "Té o café sin azúcar." },
      en: { side: "A sprinkle of cinnamon on top.", dessert: "It's already sweet, no dessert needed.", drink: "Tea or coffee, no sugar." },
    },
  },
  {
    id: "banana-oat-smoothie",
    category: "snack",
    name: { es: "Batido de banana y avena", en: "Banana and oat smoothie" },
    description: { es: "Cremoso y rendidor, ideal para la mañana o la tarde.", en: "Creamy and filling, great for morning or afternoon." },
    emoji: "🍌",
    timeMinutes: 5,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 2,
    baseCalories: 250,
    protein: "veg",
    cuisine: "fresh",
    dietTags: ["vegetarian"],
    goalTags: ["fast", "healthy"],
    ingredients: [
      { name: "Banana", category: "Frutas", qty: "1" },
      { name: "Avena", category: "Almacén", qty: "3 cdas" },
      { name: "Leche", category: "Lácteos", qty: "1 taza" },
    ],
    steps: {
      es: ["Licuá la banana, la avena y la leche hasta que quede cremoso.", "Serví bien frío."],
      en: ["Blend the banana, oats and milk until creamy.", "Serve very cold."],
    },
    tips: {
      es: ["Congelá la banana en trozos antes de licuar para que quede más cremoso."],
      en: ["Freeze the banana in chunks beforehand for an extra-creamy texture."],
    },
    healthBenefits: {
      es: ["La avena aporta fibra que da saciedad duradera.", "La banana suma potasio y energía natural."],
      en: ["Oats provide fiber for lasting fullness.", "Banana adds potassium and natural energy."],
    },
    pairing: {
      es: { side: "Nada más, ya es una comida líquida completa.", dessert: "Una pizca de canela arriba.", drink: "Se toma solo, es la bebida." },
      en: { side: "Nothing else, it's already a complete drink.", dessert: "A pinch of cinnamon on top.", drink: "It's the drink itself." },
    },
  },
  {
    id: "fresh-cheese-cherry-tomato",
    category: "snack",
    name: { es: "Queso fresco con tomate cherry", en: "Fresh cheese with cherry tomatoes" },
    description: { es: "Liviano, salado y listo en segundos.", en: "Light, savory and ready in seconds." },
    emoji: "🧀",
    timeMinutes: 3,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 2,
    baseCalories: 180,
    protein: "veg",
    cuisine: "mediterranean",
    dietTags: ["vegetarian", "glutenFree"],
    goalTags: ["fast", "healthy", "cheap"],
    ingredients: [
      { name: "Queso fresco", category: "Lácteos", qty: "80g" },
      { name: "Tomate cherry", category: "Verduras", qty: "6" },
      { name: "Aceite de oliva", category: "Almacén", qty: "1 cda" },
    ],
    steps: {
      es: ["Cortá el queso en cubos.", "Mezclá con los tomates cherry y un chorrito de aceite de oliva."],
      en: ["Cut the cheese into cubes.", "Toss with the cherry tomatoes and a drizzle of olive oil."],
    },
    tips: {
      es: ["Un poco de orégano arriba le suma sabor sin esfuerzo."],
      en: ["A pinch of oregano on top adds flavor with zero effort."],
    },
    healthBenefits: {
      es: ["El queso fresco aporta calcio y proteína con menos grasa que otros quesos.", "El tomate suma licopeno y vitamina C."],
      en: ["Fresh cheese provides calcium and protein with less fat than other cheeses.", "Tomato adds lycopene and vitamin C."],
    },
    pairing: {
      es: { side: "Unas tostadas finas.", dessert: "Fruta fresca.", drink: "Agua con gas y limón." },
      en: { side: "A few thin crackers.", dessert: "Fresh fruit.", drink: "Sparkling water with lemon." },
    },
  },
  {
    id: "homemade-popcorn",
    category: "snack",
    name: { es: "Palomitas de maíz caseras", en: "Homemade popcorn" },
    description: { es: "El snack crocante sin culpa, sin aditivos raros.", en: "The guilt-free crunchy snack, no weird additives." },
    emoji: "🍿",
    timeMinutes: 8,
    difficulty: "Easy",
    baseServings: 2,
    baseCostUSD: 1,
    baseCalories: 120,
    protein: "veg",
    cuisine: "comfort",
    dietTags: ["vegan", "glutenFree", "dairyFree"],
    goalTags: ["cheap", "healthy", "easy"],
    ingredients: [
      { name: "Maíz pisingallo", category: "Almacén", qty: "1/2 taza" },
      { name: "Aceite", category: "Almacén", qty: "1 cda" },
      { name: "Sal", category: "Almacén", qty: "a gusto" },
    ],
    steps: {
      es: ["Calentá el aceite en una olla con tapa.", "Agregá el maíz, tapá y esperá a que reviente todo.", "Salá y listo."],
      en: ["Heat the oil in a pot with a lid.", "Add the corn, cover, and wait for it all to pop.", "Salt and enjoy."],
    },
    tips: {
      es: ["Evitá la versión de microondas industrial: tiene mucho sodio y grasas trans."],
      en: ["Skip the industrial microwave version — it's loaded with sodium and trans fats."],
    },
    healthBenefits: {
      es: ["Es un cereal integral: aporta fibra y pocas calorías por porción.", "Te da volumen y sensación de saciedad sin exceso calórico."],
      en: ["It's a whole grain: fiber-rich and low-calorie per serving.", "It gives you volume and fullness without excess calories."],
    },
    pairing: {
      es: { side: "Un toque de queso rallado o pimentón.", dessert: "No necesita postre.", drink: "Agua con gas." },
      en: { side: "A touch of grated cheese or paprika.", dessert: "No dessert needed.", drink: "Sparkling water." },
    },
  },
  {
    id: "cucumber-cream-cheese",
    category: "snack",
    name: { es: "Bastones de pepino con queso crema", en: "Cucumber sticks with cream cheese" },
    description: { es: "Fresco, liviano y perfecto para el calor.", en: "Fresh, light and perfect for hot days." },
    emoji: "🥒",
    timeMinutes: 4,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 1,
    baseCalories: 130,
    protein: "veg",
    cuisine: "fresh",
    dietTags: ["vegetarian", "glutenFree", "light"],
    goalTags: ["fast", "healthy", "lowCalorie"],
    ingredients: [
      { name: "Pepino", category: "Verduras", qty: "1" },
      { name: "Queso crema", category: "Lácteos", qty: "3 cdas" },
    ],
    steps: {
      es: ["Cortá el pepino en bastones.", "Serví con el queso crema para untar."],
      en: ["Cut the cucumber into sticks.", "Serve with cream cheese for dipping."],
    },
    tips: {
      es: ["Sumale eneldo o ciboulette picado si tenés."],
      en: ["Add chopped dill or chives if you have some."],
    },
    healthBenefits: {
      es: ["El pepino es casi todo agua: hidrata y aporta muy pocas calorías.", "El queso crema suma un poco de calcio y grasa saciante."],
      en: ["Cucumber is mostly water: hydrating and very low-calorie.", "Cream cheese adds a bit of calcium and satisfying fat."],
    },
    pairing: {
      es: { side: "Unas galletas de arroz.", dessert: "Fruta fresca.", drink: "Agua saborizada." },
      en: { side: "A few rice cakes.", dessert: "Fresh fruit.", drink: "Infused water." },
    },
  },
  {
    id: "wholegrain-toast-cheese-tomato",
    category: "snack",
    name: { es: "Tostada integral con queso y tomate", en: "Whole-grain toast with cheese and tomato" },
    description: { es: "Simple, equilibrada y rinde para calmar el hambre real.", en: "Simple, balanced, and enough to actually curb hunger." },
    emoji: "🍅",
    timeMinutes: 5,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 2,
    baseCalories: 210,
    protein: "veg",
    cuisine: "mediterranean",
    dietTags: ["vegetarian"],
    goalTags: ["fast", "cheap", "healthy"],
    ingredients: [
      { name: "Pan integral", category: "Almacén", qty: "1 rebanada" },
      { name: "Queso", category: "Lácteos", qty: "40g" },
      { name: "Tomate", category: "Verduras", qty: "1/2" },
    ],
    steps: {
      es: ["Tostá el pan.", "Agregá el queso y el tomate en fetas encima."],
      en: ["Toast the bread.", "Add the cheese and sliced tomato on top."],
    },
    tips: {
      es: ["Si tenés horno o sandwichera, gratinala unos minutos."],
      en: ["If you have an oven or sandwich press, melt it for a few minutes."],
    },
    healthBenefits: {
      es: ["El pan integral aporta más fibra que el pan blanco.", "El tomate suma vitamina C y licopeno."],
      en: ["Whole-grain bread provides more fiber than white bread.", "Tomato adds vitamin C and lycopene."],
    },
    pairing: {
      es: { side: "Orégano y un chorrito de aceite de oliva.", dessert: "Fruta de postre.", drink: "Té o mate." },
      en: { side: "Oregano and a drizzle of olive oil.", dessert: "Fruit for dessert.", drink: "Tea or herbal mate." },
    },
  },
  {
    id: "greek-yogurt-honey-walnuts",
    category: "snack",
    name: { es: "Yogur griego con miel y nueces", en: "Greek yogurt with honey and walnuts" },
    description: { es: "Denso, cremoso y con proteína real.", en: "Thick, creamy, and with real protein." },
    emoji: "🍯",
    timeMinutes: 2,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 2,
    baseCalories: 230,
    protein: "veg",
    cuisine: "mediterranean",
    dietTags: ["vegetarian", "highProtein", "glutenFree"],
    goalTags: ["fast", "healthy", "protein"],
    ingredients: [
      { name: "Yogur griego", category: "Lácteos", qty: "1 pote" },
      { name: "Miel", category: "Almacén", qty: "1 cda" },
      { name: "Nueces", category: "Almacén", qty: "1 puñado" },
    ],
    steps: {
      es: ["Serví el yogur en un bowl.", "Agregá la miel y las nueces picadas arriba."],
      en: ["Serve the yogurt in a bowl.", "Add the honey and chopped walnuts on top."],
    },
    tips: {
      es: ["El yogur griego tiene el doble de proteína que el yogur común."],
      en: ["Greek yogurt has twice the protein of regular yogurt."],
    },
    healthBenefits: {
      es: ["Alto en proteína, ayuda a mantenerte saciada mucho más tiempo.", "Las nueces aportan Omega-3 de origen vegetal."],
      en: ["High in protein, keeps you full for much longer.", "Walnuts provide plant-based Omega-3s."],
    },
    pairing: {
      es: { side: "Frutos rojos frescos.", dessert: "Ya es un postre en sí mismo.", drink: "Café o té." },
      en: { side: "Fresh berries.", dessert: "It's already a dessert on its own.", drink: "Coffee or tea." },
    },
  },
  {
    id: "oat-date-bars",
    category: "snack",
    name: { es: "Barritas caseras de avena y dátiles", en: "Homemade oat and date bars" },
    description: { es: "Dulces naturalmente, sin azúcar agregada.", en: "Naturally sweet, with no added sugar." },
    emoji: "🍪",
    timeMinutes: 15,
    difficulty: "Easy",
    baseServings: 6,
    baseCostUSD: 4,
    baseCalories: 160,
    protein: "veg",
    cuisine: "comfort",
    dietTags: ["vegan", "dairyFree"],
    goalTags: ["healthy", "useWhatIHave"],
    ingredients: [
      { name: "Avena", category: "Almacén", qty: "2 tazas" },
      { name: "Dátiles", category: "Frutas", qty: "1 taza" },
      { name: "Manteca de maní", category: "Almacén", qty: "3 cdas" },
    ],
    steps: {
      es: ["Procesá los dátiles hasta formar una pasta pegajosa.", "Mezclá con la avena y la manteca de maní.", "Aplastá en una fuente y llevá a la heladera 1 hora, después cortá en barras."],
      en: ["Process the dates into a sticky paste.", "Mix with the oats and peanut butter.", "Press into a dish, chill for 1 hour, then cut into bars."],
    },
    tips: {
      es: ["Guardalas en la heladera hasta 1 semana: son ideales para preparar el domingo."],
      en: ["They keep in the fridge for up to a week — perfect to prep on Sunday."],
    },
    healthBenefits: {
      es: ["Los dátiles endulzan de forma natural y aportan fibra y potasio.", "La avena da energía sostenida sin picos de azúcar."],
      en: ["Dates sweeten naturally and provide fiber and potassium.", "Oats give sustained energy without sugar spikes."],
    },
    pairing: {
      es: { side: "Nada más, es un snack completo.", dessert: "—", drink: "Té o café sin azúcar." },
      en: { side: "Nothing else, it's a complete snack.", dessert: "—", drink: "Tea or coffee, no sugar." },
    },
  },
  {
    id: "seasonal-fruit-salad",
    category: "snack",
    name: { es: "Ensalada de frutas de estación", en: "Seasonal fruit salad" },
    description: { es: "Fresca, dulce e hidratante.", en: "Fresh, sweet and hydrating." },
    emoji: "🍉",
    timeMinutes: 8,
    difficulty: "Easy",
    baseServings: 2,
    baseCostUSD: 3,
    baseCalories: 140,
    protein: "veg",
    cuisine: "fresh",
    dietTags: ["vegan", "glutenFree", "dairyFree", "light"],
    goalTags: ["healthy", "lowCalorie", "cheap"],
    ingredients: [
      { name: "Frutas de estación variadas", category: "Frutas", qty: "3 tazas" },
      { name: "Limón", category: "Frutas", qty: "1/2" },
    ],
    steps: {
      es: ["Cortá todas las frutas en trozos parejos.", "Mezclá en un bowl y exprimí un poco de limón encima."],
      en: ["Cut all the fruit into even pieces.", "Toss in a bowl and squeeze a bit of lemon on top."],
    },
    tips: {
      es: ["El limón evita que las frutas como la manzana o la banana se pongan marrones."],
      en: ["Lemon keeps fruits like apple or banana from browning."],
    },
    healthBenefits: {
      es: ["Aporta vitaminas y antioxidantes variados según la fruta que uses.", "Es naturalmente baja en calorías e hidratante."],
      en: ["Provides varied vitamins and antioxidants depending on the fruit used.", "Naturally low-calorie and hydrating."],
    },
    pairing: {
      es: { side: "Un puñado de granola arriba.", dessert: "Ya es el postre.", drink: "Agua o té frío sin azúcar." },
      en: { side: "A handful of granola on top.", dessert: "It's already the dessert.", drink: "Water or unsweetened iced tea." },
    },
  },
  {
    id: "ham-cheese-roll",
    category: "snack",
    name: { es: "Roll de jamón y queso", en: "Ham and cheese roll" },
    description: { es: "Simple, sin pan, rápido de armar.", en: "Simple, bread-free, quick to put together." },
    emoji: "🧻",
    timeMinutes: 4,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 2,
    baseCalories: 170,
    protein: "veg",
    cuisine: "comfort",
    dietTags: ["glutenFree", "highProtein"],
    goalTags: ["fast", "protein", "easy"],
    ingredients: [
      { name: "Jamón cocido", category: "Carnes", qty: "3 fetas" },
      { name: "Queso", category: "Lácteos", qty: "3 fetas" },
    ],
    steps: {
      es: ["Colocá una feta de queso sobre cada feta de jamón.", "Enrollá bien apretado y listo."],
      en: ["Place a slice of cheese on each slice of ham.", "Roll tightly and you're done."],
    },
    tips: {
      es: ["Sumale un poco de rúcula adentro para más fibra."],
      en: ["Add a bit of arugula inside for more fiber."],
    },
    healthBenefits: {
      es: ["Aporta proteína magra sin necesidad de pan ni carbohidratos extra.", "Buena opción si buscás algo bajo en carbohidratos."],
      en: ["Provides lean protein with no need for bread or extra carbs.", "A good option if you're looking for something low-carb."],
    },
    pairing: {
      es: { side: "Tomates cherry al costado.", dessert: "Fruta fresca.", drink: "Agua o té." },
      en: { side: "Cherry tomatoes on the side.", dessert: "Fresh fruit.", drink: "Water or tea." },
    },
  },
  {
    id: "rice-cakes-avocado",
    category: "snack",
    name: { es: "Galletas de arroz con palta", en: "Rice cakes with avocado" },
    description: { es: "Livianas y crocantes, con la cremosidad de la palta.", en: "Light and crunchy, with the creaminess of avocado." },
    emoji: "🍘",
    timeMinutes: 4,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 2,
    baseCalories: 160,
    protein: "veg",
    cuisine: "fresh",
    dietTags: ["vegan", "glutenFree", "dairyFree"],
    goalTags: ["fast", "healthy", "lowCalorie"],
    ingredients: [
      { name: "Galletas de arroz", category: "Almacén", qty: "2" },
      { name: "Palta", category: "Frutas", qty: "1/2" },
    ],
    steps: {
      es: ["Pisá la palta con un poco de sal y limón.", "Untala sobre las galletas de arroz."],
      en: ["Mash the avocado with a bit of salt and lemon.", "Spread it on the rice cakes."],
    },
    tips: {
      es: ["Semillas de sésamo o chía arriba suman textura y nutrientes."],
      en: ["Sesame or chia seeds on top add texture and nutrients."],
    },
    healthBenefits: {
      es: ["Las galletas de arroz son livianas y bajas en calorías.", "La palta aporta grasas saludables que dan saciedad."],
      en: ["Rice cakes are light and low-calorie.", "Avocado provides healthy fats that keep you full."],
    },
    pairing: {
      es: { side: "Tomate en rodajas finas.", dessert: "Fruta fresca.", drink: "Agua con gas." },
      en: { side: "Thin tomato slices.", dessert: "Fresh fruit.", drink: "Sparkling water." },
    },
  },
  {
    id: "green-smoothie",
    category: "snack",
    name: { es: "Smoothie verde de espinaca, banana y manzana", en: "Green smoothie with spinach, banana and apple" },
    description: { es: "Refrescante y una forma fácil de sumar verduras.", en: "Refreshing, and an easy way to sneak in more greens." },
    emoji: "🥬",
    timeMinutes: 5,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 2,
    baseCalories: 160,
    protein: "veg",
    cuisine: "fresh",
    dietTags: ["vegan", "glutenFree", "dairyFree", "light"],
    goalTags: ["healthy", "fast", "lowCalorie"],
    ingredients: [
      { name: "Espinaca", category: "Verduras", qty: "1 puñado" },
      { name: "Banana", category: "Frutas", qty: "1" },
      { name: "Manzana", category: "Frutas", qty: "1" },
    ],
    steps: {
      es: ["Licuá la espinaca, la banana, la manzana y un poco de agua.", "Serví bien frío."],
      en: ["Blend the spinach, banana, apple and a bit of water.", "Serve very cold."],
    },
    tips: {
      es: ["No se siente el sabor de la espinaca: la banana y la manzana lo tapan."],
      en: ["You won't taste the spinach — the banana and apple mask it."],
    },
    healthBenefits: {
      es: ["La espinaca aporta hierro y vitamina K.", "Las frutas suman fibra y dulzor natural, sin azúcar agregada."],
      en: ["Spinach provides iron and vitamin K.", "The fruit adds fiber and natural sweetness, with no added sugar."],
    },
    pairing: {
      es: { side: "Nada más, ya es la bebida y la merienda.", dessert: "—", drink: "Se toma solo." },
      en: { side: "Nothing else, it's already the drink and the snack.", dessert: "—", drink: "It's the drink itself." },
    },
  },
  {
    id: "quick-scrambled-eggs",
    category: "snack",
    name: { es: "Huevos revueltos rápidos", en: "Quick scrambled eggs" },
    description: { es: "El snack salado que llena de verdad en minutos.", en: "The savory snack that actually fills you up in minutes." },
    emoji: "🍳",
    timeMinutes: 6,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 1,
    baseCalories: 200,
    protein: "egg",
    cuisine: "comfort",
    dietTags: ["vegetarian", "glutenFree", "highProtein"],
    goalTags: ["fast", "cheap", "protein"],
    ingredients: [
      { name: "Huevos", category: "Huevos", qty: "2" },
      { name: "Sal y pimienta", category: "Especias", qty: "a gusto" },
    ],
    steps: {
      es: ["Batí los huevos con sal y pimienta.", "Cociná en una sartén a fuego bajo, revolviendo, hasta que cuajen."],
      en: ["Beat the eggs with salt and pepper.", "Cook in a pan over low heat, stirring, until set."],
    },
    tips: {
      es: ["Fuego bajo y revolver seguido: así quedan cremosos, no gomosos."],
      en: ["Low heat and frequent stirring keeps them creamy, not rubbery."],
    },
    healthBenefits: {
      es: ["Proteína completa que sostiene el hambre por horas.", "Aporta vitamina D y colina, buena para el cerebro."],
      en: ["Complete protein that keeps hunger away for hours.", "Provides vitamin D and choline, good for the brain."],
    },
    pairing: {
      es: { side: "Una tostada integral.", dessert: "Fruta fresca.", drink: "Café o mate." },
      en: { side: "A slice of whole-grain toast.", dessert: "Fresh fruit.", drink: "Coffee or herbal mate." },
    },
  },
  {
    id: "almonds-raisins-mix",
    category: "snack",
    name: { es: "Mix de almendras y pasas", en: "Almond and raisin mix" },
    description: { es: "El clásico snack de cartera o mochila.", en: "The classic bag or backpack snack." },
    emoji: "🍇",
    timeMinutes: 1,
    difficulty: "Easy",
    baseServings: 1,
    baseCostUSD: 1,
    baseCalories: 180,
    protein: "veg",
    cuisine: "fresh",
    dietTags: ["vegan", "glutenFree", "dairyFree"],
    goalTags: ["fast", "cheap", "easy"],
    ingredients: [
      { name: "Almendras", category: "Almacén", qty: "15" },
      { name: "Pasas de uva", category: "Almacén", qty: "2 cdas" },
    ],
    steps: {
      es: ["Mezclá las almendras y las pasas en un pote chico.", "Llevalo con vos."],
      en: ["Mix the almonds and raisins in a small container.", "Take it with you."],
    },
    tips: {
      es: ["Una porción medida (no todo el paquete) evita pasarte de calorías."],
      en: ["A measured portion (not the whole bag) keeps the calories in check."],
    },
    healthBenefits: {
      es: ["Las almendras aportan grasas buenas, vitamina E y magnesio.", "Las pasas dan energía rápida gracias a sus azúcares naturales."],
      en: ["Almonds provide good fats, vitamin E and magnesium.", "Raisins give quick energy thanks to their natural sugars."],
    },
    pairing: {
      es: { side: "Nada más, es un snack para llevar.", dessert: "—", drink: "Agua." },
      en: { side: "Nothing else, it's a grab-and-go snack.", dessert: "—", drink: "Water." },
    },
  },
  {
    id: "light-fruit-jelly",
    category: "snack",
    name: { es: "Gelatina light con frutas", en: "Sugar-free jelly with fruit" },
    description: { es: "Dulce, liviana y prácticamente sin calorías.", en: "Sweet, light, and practically calorie-free." },
    emoji: "🍮",
    timeMinutes: 5,
    difficulty: "Easy",
    baseServings: 2,
    baseCostUSD: 1,
    baseCalories: 60,
    protein: "veg",
    cuisine: "fresh",
    dietTags: ["vegetarian", "glutenFree", "light"],
    goalTags: ["lowCalorie", "cheap", "healthy"],
    ingredients: [
      { name: "Gelatina light", category: "Almacén", qty: "1 sobre" },
      { name: "Frutas picadas", category: "Frutas", qty: "1 taza" },
    ],
    steps: {
      es: ["Preparás la gelatina light según el paquete.", "Agregá las frutas picadas antes de que cuaje en la heladera."],
      en: ["Prepare the sugar-free jelly according to the package.", "Add the chopped fruit before it sets in the fridge."],
    },
    tips: {
      es: ["Elegí frutas que no sean muy acuosas, como banana o durazno, para que no aguaden la gelatina."],
      en: ["Choose fruits that aren't too watery, like banana or peach, so the jelly doesn't get diluted."],
    },
    healthBenefits: {
      es: ["Es una opción dulce con muy pocas calorías, ideal si buscás cuidar el azúcar.", "La fruta suma fibra y vitaminas reales."],
      en: ["A sweet option with very few calories, great if you're watching sugar.", "The fruit adds real fiber and vitamins."],
    },
    pairing: {
      es: { side: "Nada más.", dessert: "Ya es el postre.", drink: "Agua o té." },
      en: { side: "Nothing else.", dessert: "It's already the dessert.", drink: "Water or tea." },
    },
  },
];
