import type { Lang } from "./types";

export const strings = {
  es: {
    appName: "Cocina Sin Estrés",
    tagline: "Método interactivo para resolver la carga mental de la comida diaria",
    hero: {
      headline: "Cocina Sin Estrés",
      subheadline: "Método interactivo para resolver la carga mental de la comida diaria",
      support: "Aprendé a organizar tus comidas, resolver qué cocinar cada día y armar tu lista de compras sin improvisar, sin pensar de cero y sin vivir preguntándote “¿qué hago de comer hoy?”",
      cta: "Empezar mi diagnóstico",
      secondaryCta: "Ver cómo funciona",
      microcopy: "No es un ebook. No es un PDF. Es tu Chef IA, las 24 horas.",
    },
    howItWorks: {
      title: "Cómo funciona",
      steps: [
        { title: "Contanos tu caos", body: "Un diagnóstico de 3 preguntas para entender qué te está pasando hoy." },
        { title: "Te damos una estructura", body: "El Método Cena Resuelta™ convierte tu energía, tiempo e ingredientes en una decisión." },
        { title: "Resolvés y seguís", body: "Recetas, menú semanal y lista de compras — sin pensar todo desde cero cada día." },
      ],
      cta: "Empezar mi diagnóstico",
    },
    language: {
      title: "Elegí tu idioma",
      subtitle: "Usá la app en el idioma que prefieras.",
    },
    country: {
      title: "¿Dónde estás cocinando hoy?",
      subtitle: "Adaptamos ingredientes, precios, unidades y nombres locales.",
      detect: "Usar mi ubicación",
      other: "Otro",
    },
    diagnostic: {
      title: "¿Qué tipo de caos tenés en la cocina?",
      q1: {
        title: "¿Qué te pasa más seguido al final del día?",
        options: [
          "No sé qué cocinar.",
          "Tengo comida, pero no ideas.",
          "Termino haciendo siempre lo mismo.",
          "Pido delivery por cansancio.",
          "Compro sin plan y después me falta algo.",
        ],
      },
      q2: {
        title: "¿Cuánta energía tenés normalmente cuando llega la hora de cocinar?",
        options: ["Cero energía.", "Algo de energía.", "Depende del día.", "Me gusta cocinar, pero necesito orden."],
      },
      q3: {
        title: "¿Qué necesitás resolver primero?",
        options: ["Ideas rápidas para hoy.", "Menú semanal.", "Lista de compras.", "Comer mejor sin complicarme.", "Ahorrar tiempo y dinero."],
      },
      resultTitle: "Tu diagnóstico",
      resultCta: "Ver mi plan recomendado →",
      profiles: {
        improvisadora: {
          title: "La improvisadora agotada",
          body: "Necesitás dejar de decidir desde cero cada noche y tener opciones rápidas según tu tiempo y energía.",
        },
        repetidora: {
          title: "La repetidora de siempre lo mismo",
          body: "Necesitás variedad simple, no recetas complicadas.",
        },
        compradora: {
          title: "La compradora sin plan",
          body: "Necesitás conectar menú + lista de compras para dejar de comprar al azar.",
        },
        delivery: {
          title: "La delivery-dependiente",
          body: "Necesitás un menú de emergencia para esos días donde no hay energía.",
        },
        organizada: {
          title: "La organizada frustrada",
          body: "Ya intentaste planificar, pero necesitás una estructura más flexible y fácil de sostener.",
        },
      },
    },
    method: {
      eyebrow: "El Método",
      title: "El Método Cena Resuelta™",
      subtitle: "Una forma simple de elegir qué cocinar según tu tiempo, tus ingredientes y tu energía real del día.",
      energyTitle: "Elegí tu energía",
      energyOptions: ["Estoy destruida.", "Tengo energía media.", "Hoy puedo cocinar un poco más."],
      timeTitle: "Elegí tu tiempo",
      timeOptions: ["10 minutos", "20 minutos", "30 minutos"],
      ingredientsTitle: "Elegí qué tenés",
      ingredientsOptions: ["Pollo", "Carne", "Huevos", "Verduras", "Arroz o pasta", "Lo que haya en la heladera"],
      cta: "Resolver mi comida →",
    },
    mode: {
      title: "¿Qué necesitás resolver hoy?",
      cards: [
        { key: "solve", emoji: "🍽", label: "Resolver la comida de hoy" },
        { key: "useWhatIHave", emoji: "🥬", label: "Cocinar con lo que tengo" },
        { key: "adaptFavorite", emoji: "❤️", label: "Adaptar una receta favorita" },
        { key: "surprise", emoji: "🎲", label: "Sorprendeme" },
        { key: "shoppingList", emoji: "🛒", label: "Armar lista de compras" },
        { key: "calories", emoji: "🔥", label: "Calorías y nutrición" },
        { key: "savings", emoji: "💰", label: "Cocinar vs. delivery" },
      ],
    },
    dashboard: {
      title: "Tu método, paso a paso",
      subtitle: "No es una colección de recetas. Es una forma guiada de resolver la comida diaria.",
      methodBanner: {
        eyebrow: "La parte educativa",
        title: "📖 Aprendé el Método",
        subtitle: "5 capítulos cortos: por qué la comida diaria estresa y cómo resolverlo para siempre.",
        cta: "Recorrer el método →",
      },
      quickTitle: "O andá directo a lo que necesitás",
      sections: [
        {
          key: "today",
          title: "Resolver hoy",
          cards: [
            { key: "solve", emoji: "🍽", label: "¿Qué cocino hoy?" },
            { key: "emergency", emoji: "🆘", label: "Menú de emergencia" },
            { key: "under30", emoji: "⏱", label: "Recetas en 30 minutos o menos" },
            { key: "snack", emoji: "🥨", label: "Snack saludable al toque" },
          ],
        },
        {
          key: "week",
          title: "Organizar la semana",
          cards: [
            { key: "weeklyPlanner", emoji: "📅", label: "Planificador semanal" },
            { key: "shoppingList", emoji: "🛒", label: "Lista de compras inteligente" },
            { key: "portions", emoji: "🍽", label: "Cálculo por comensales" },
            { key: "occasions", emoji: "🎉", label: "Menús para ocasiones especiales" },
          ],
        },
      ],
      savedRecipesLink: "❤️ Mis recetas guardadas",
      moreOptions: "Ver todas las opciones",
    },
    intro: {
      message: "Hola, soy tu Chef AI personal. Resuelvo tu comida de hoy. Solo necesito algunos datos.",
      cta: "Dale, vamos",
    },
    people: {
      title: "¿Cuántas personas comen hoy?",
      options: ["Solo yo", "2 personas", "3–4 personas", "5 o más"],
    },
    children: {
      title: "¿Hay chicos comiendo hoy?",
      yes: "Sí",
      no: "No",
      agesTitle: "¿Qué edades?",
      ages: ["0–2", "3–5", "6–9", "10–14", "15+"],
    },
    time: {
      title: "¿Cuánto tiempo tenés?",
      options: ["15 minutos", "20 minutos", "30 minutos", "45 minutos", "Tengo más tiempo", "Sorprendeme"],
    },
    ingredients: {
      title: "¿Qué tenés en casa?",
      placeholder: "Escribí un ingrediente y presioná Enter…",
      categories: ["Carnes", "Verduras", "Lácteos", "Huevos", "Pastas", "Almacén", "Frutas", "Especias"],
      suggestedLabel: "Sugeridos para vos",
    },
    shoppingPref: {
      title: "¿Querés cocinar solo con lo que ya tenés?",
      options: ["Sí, no me hagas comprar nada", "Puedo comprar algunos ingredientes", "Sin preferencia"],
    },
    dietary: {
      title: "¿Alguna restricción o necesidad alimentaria?",
      options: [
        "Sin restricciones", "Vegetariano", "Vegano", "Sin gluten", "Sin lácteos",
        "Bajo en sodio", "Estilo diabetes-friendly", "Alto en proteína", "Bajo en carbohidratos",
        "Apto para chicos", "Liviano",
      ],
    },
    preference: {
      title: "¿Qué se te antoja hoy?",
      options: [
        "Pollo", "Carne", "Pescado", "Pasta", "Vegetariano", "Liviano y fresco",
        "Comfort food", "Mexicana", "Mediterránea", "Asiática", "Sorprendeme",
      ],
    },
    goal: {
      title: "¿Qué es lo más importante hoy?",
      options: [
        "Cocinar rápido", "Gastar menos", "Comer más sano", "Usar lo que tengo",
        "Más proteína", "Menos calorías", "No pensar demasiado",
      ],
    },
    thinking: {
      title: "Estoy resolviendo tu comida…",
      lines: [
        "Analizando tus ingredientes…",
        "Revisando tu tiempo disponible…",
        "Adaptando a tu país…",
        "Calculando lo que falta…",
        "Balanceando la nutrición…",
        "Comparando cocinar vs. delivery…",
        "Armando tu mejor opción…",
      ],
    },
    result: {
      title: "Ya resolví tu comida.",
      congrats: "¡Elegiste bien! 🎉",
      solvedIn: "Resolviste tu menú en {s} segundos ⚡",
      solvedInFooter: "Así de rápido es cocinar cuando hay orden.",
      servings: "porciones",
      stepsLabel: "Preparación",
      timeLabel: "Tiempo",
      difficulty: "Dificultad",
      cost: "Costo estimado",
      calories: "kcal por porción",
      viewRecipe: "Ver receta",
      dislike: "No me convence",
      save: "Guardar / copiar",
      another: "Otra opción",
      saveFavorite: "❤️ Guardar receta",
      savedFavorite: "❤️ Guardada",
    },
    why: {
      title: "Por qué elegí esto",
    },
    pairing: {
      title: "Cómo disfrutarlo",
      side: "Acompañalo con",
      dessert: "De postre",
      drink: "Para tomar",
    },
    actions: {
      copyRecipe: "📋 Copiar receta",
      copyShoppingList: "📋 Copiar lista de compras",
      more: "¿Querés que calcule algo más?",
      shoppingList: "Lista de compras",
      calories: "Calorías y nutrición",
      savings: "Ahorro vs. delivery",
      anotherOption: "Otra opción",
      adaptRecipe: "Adaptar receta",
      discover: "Descubrí Cocina Sin Estrés",
    },
    reject: {
      message: "No hay problema. ¿Qué te gustaría cambiar?",
      options: [
        { key: "faster", label: "Más rápido" },
        { key: "cheaper", label: "Más barato" },
        { key: "healthier", label: "Más sano" },
        { key: "moreProtein", label: "Más proteína" },
        { key: "lowerCalories", label: "Menos calorías" },
        { key: "differentProtein", label: "Otra proteína" },
        { key: "sameIngredients", label: "Mismos ingredientes" },
        { key: "buyMore", label: "Puedo comprar más" },
        { key: "kidFriendly", label: "Apto para chicos" },
        { key: "surpriseAgain", label: "Sorprendeme de nuevo" },
      ],
    },
    favorite: {
      howTitle: "¿Cómo querés agregarla?",
      typePaste: "Escribir / pegar receta",
      pasteLink: "Pegar un link",
      uploadPhoto: "Subir una foto",
      uploadPdf: "Subir un PDF",
      futurePlaceholder: "El análisis de foto y PDF se va a poder conectar más adelante. Por ahora, pegá el texto de tu receta.",
      placeholder: "Pegá acá tu receta favorita…",
      adaptTitle: "¿Cómo la adapto?",
      adaptOptions: [
        "Más rápida", "Más sana", "Más barata", "Más proteína", "Menos calorías",
        "Apto para chicos", "Sin gluten", "Sin lácteos", "Con lo que ya tengo", "Adaptar a la familia de hoy",
      ],
      submit: "Adaptar receta →",
    },
    nutrition: {
      title: "Calorías y nutrición",
      disclaimer: "Valores estimados.",
      protein: "Proteína",
      carbs: "Carbohidratos",
      fat: "Grasas",
      fiber: "Fibra",
      sugar: "Azúcar",
      sodium: "Sodio",
      score: "Puntaje nutricional",
      benefitsTitle: "Beneficios de este plato",
    },
    savingsModule: {
      title: "Cocinar vs. delivery",
      disclaimer: "Ahorro estimado.",
      cooking: "Cocinar esto",
      delivery: "Delivery estimado",
      todaySavings: "Ahorrás hoy",
      monthly: "Ahorro estimado al mes",
    },
    shoppingListModule: {
      title: "Lista de compras",
      subtitle: "Solo lo que te falta.",
      estimatedCost: "Costo estimado",
      nothingMissing: "Ya tenés todo lo que necesitás. ✅",
    },
    weeklyPlanner: {
      title: "Planificador semanal",
      subtitle: "5 días resueltos, con una sola lista de compras para toda la semana.",
      generatingTitle: "Armando tu semana…",
      dayLabels: ["Día 1", "Día 2", "Día 3", "Día 4", "Día 5"],
      shoppingListTitle: "Lista de compras de la semana",
      cta: "Armar mi semana →",
      viewDay: "Ver receta",
      backToWeek: "← Volver a la semana",
    },
    occasions: {
      title: "Menús para ocasiones especiales",
      subtitle: "Elegí la ocasión y te armo un menú listo.",
      menuSubtitle: "Tocá una receta para verla completa.",
    },
    savedRecipes: {
      title: "Mis recetas guardadas",
      empty: "Todavía no guardaste ninguna receta. Cuando resuelvas una comida, tocá “Guardar receta”.",
      remove: "Quitar",
      savedToast: "Guardada en Mis recetas",
    },
    guide: {
      title: "Guía interactiva",
      subtitle: "Capítulos breves para entender el método, no solo usarlo.",
      chapters: [
        {
          title: "El verdadero problema no es cocinar",
          body: "La comida diaria se vuelve estresante porque no es una sola tarea. Es decidir, revisar ingredientes, calcular tiempos, pensar en gustos, comprar, cocinar y repetirlo todos los días.",
          quote: "No estás cansada de cocinar. Estás cansada de decidir qué cocinar.",
        },
        {
          title: "Los 4 errores que vuelven caótica la comida diaria",
          errors: [
            "Comprar sin menú.",
            "Buscar recetas cuando ya tenés hambre.",
            "Pensar comidas sueltas en vez de bloques.",
            "Querer cocinar perfecto cuando solo necesitás resolver simple.",
          ],
          quote: "La cocina diaria no necesita inspiración. Necesita estructura.",
        },
        {
          title: "El menú de emergencia",
          body: "Toda persona necesita opciones simples para los días de cansancio — algo a lo que recurrir sin pensar, sin culpa y sin depender del delivery.",
          quote: "Cuando tenés un menú de emergencia, el cansancio deja de decidir por vos.",
        },
        {
          title: "Cómo armar una semana sin drama",
          structure: [
            "2 comidas base.",
            "2 comidas rápidas.",
            "1 comida con sobras.",
            "1 comida de emergencia.",
            "1 opción libre.",
          ],
          quote: "Un buen menú semanal no te encierra. Te libera de decidir cansada.",
        },
        {
          title: "Orden en la cocina = comida más rápida",
          structure: [
            "Vaciá y limpiá la heladera un día fijo por semana, antes de comprar.",
            "Guardá cada cosa siempre en el mismo lugar: no perdés tiempo buscando.",
            "Cociná en lotes: doblá una receta y congelá la mitad en porciones individuales.",
            "Etiquetá lo que congelás con la fecha, así no se acumula sin control.",
            "Comprá pensando en la semana completa, no comida por comida.",
          ],
          quote: "Cuando la cocina tiene orden, decidir qué cocinar deja de ser un esfuerzo.",
        },
      ],
      cta: "Volver al método",
    },
    finalCta: {
      message: "Hoy resolvimos una comida. Imaginate resolver toda tu semana así.",
      bullets: [
        "Menús semanales", "Listas de compras inteligentes", "Recetas con lo que ya tenés",
        "Calorías y nutrición", "Menús para chicos", "Menús temáticos", "Calculadora de ahorro",
      ],
      cta: "Descubrí Cocina Sin Estrés →",
      secondary: "Probar otra receta",
    },
    ui: {
      back: "← Atrás",
      backWord: "Volver",
      next: "Siguiente →",
      finish: "Ver mi resumen →",
      copied: "¡Copiado!",
      estimatedValues: "Valores estimados",
      skip: "Omitir",
      continue: "Continuar",
      loading: "Un segundo…",
    },
  },
  en: {
    appName: "Stress-Free Cooking",
    tagline: "Interactive method to solve the mental load of daily meals",
    hero: {
      headline: "Stress-Free Cooking",
      subheadline: "Interactive method to solve the mental load of daily meals",
      support: "Learn to organize your meals, decide what to cook each day, and build your shopping list — without improvising, without starting from zero, without living stuck on “what should I cook today?”",
      cta: "Start my diagnosis",
      secondaryCta: "See how it works",
      microcopy: "Not an ebook. Not a PDF. Your AI Chef, 24/7.",
    },
    howItWorks: {
      title: "How it works",
      steps: [
        { title: "Tell us your chaos", body: "A 3-question diagnosis to understand what's going on for you today." },
        { title: "We give you structure", body: "The Solved Dinner Method™ turns your energy, time and ingredients into a decision." },
        { title: "You solve it and move on", body: "Recipes, weekly menu and shopping list — without rethinking everything from scratch every day." },
      ],
      cta: "Start my diagnosis",
    },
    language: {
      title: "Choose your language",
      subtitle: "Use the app in the language you prefer.",
    },
    country: {
      title: "Where are you cooking today?",
      subtitle: "We'll adapt ingredients, prices, units and local food names.",
      detect: "Use detected location",
      other: "Other",
    },
    diagnostic: {
      title: "What kind of kitchen chaos do you have?",
      q1: {
        title: "What happens to you most often at the end of the day?",
        options: [
          "I don't know what to cook.",
          "I have food, but no ideas.",
          "I always end up making the same thing.",
          "I order delivery out of exhaustion.",
          "I buy without a plan and then something's missing.",
        ],
      },
      q2: {
        title: "How much energy do you usually have when it's time to cook?",
        options: ["Zero energy.", "Some energy.", "Depends on the day.", "I like cooking, but I need order."],
      },
      q3: {
        title: "What do you need to solve first?",
        options: ["Quick ideas for today.", "A weekly menu.", "A shopping list.", "Eating better without complicating things.", "Saving time and money."],
      },
      resultTitle: "Your diagnosis",
      resultCta: "See my recommended plan →",
      profiles: {
        improvisadora: {
          title: "The exhausted improviser",
          body: "You need to stop deciding from scratch every night and have quick options based on your time and energy.",
        },
        repetidora: {
          title: "The same-thing-every-time cook",
          body: "You need simple variety, not complicated recipes.",
        },
        compradora: {
          title: "The planless shopper",
          body: "You need to connect menu + shopping list so you stop buying at random.",
        },
        delivery: {
          title: "The delivery-dependent one",
          body: "You need an emergency menu for the days when there's no energy left.",
        },
        organizada: {
          title: "The frustrated planner",
          body: "You've already tried planning, but you need a more flexible, easier-to-sustain structure.",
        },
      },
    },
    method: {
      eyebrow: "The Method",
      title: "The Solved Dinner Method™",
      subtitle: "A simple way to choose what to cook based on your time, your ingredients and your real energy today.",
      energyTitle: "Choose your energy",
      energyOptions: ["I'm running on empty.", "I have medium energy.", "I can cook a bit more today."],
      timeTitle: "Choose your time",
      timeOptions: ["10 minutes", "20 minutes", "30 minutes"],
      ingredientsTitle: "Choose what you have",
      ingredientsOptions: ["Chicken", "Beef", "Eggs", "Vegetables", "Rice or pasta", "Whatever's in the fridge"],
      cta: "Solve my meal →",
    },
    mode: {
      title: "What do you need help with today?",
      cards: [
        { key: "solve", emoji: "🍽", label: "Solve today's meal" },
        { key: "useWhatIHave", emoji: "🥬", label: "Cook with what I have" },
        { key: "adaptFavorite", emoji: "❤️", label: "Adapt a favorite recipe" },
        { key: "surprise", emoji: "🎲", label: "Surprise me" },
        { key: "shoppingList", emoji: "🛒", label: "Create a shopping list" },
        { key: "calories", emoji: "🔥", label: "Check calories & nutrition" },
        { key: "savings", emoji: "💰", label: "Compare cooking vs delivery" },
      ],
    },
    dashboard: {
      title: "Your method, step by step",
      subtitle: "This isn't a recipe collection. It's a guided way to solve daily meals.",
      methodBanner: {
        eyebrow: "The learning part",
        title: "📖 Learn the Method",
        subtitle: "5 short chapters: why daily meals stress you out, and how to fix it for good.",
        cta: "Go through the method →",
      },
      quickTitle: "Or jump straight to what you need",
      sections: [
        {
          key: "today",
          title: "Solve today",
          cards: [
            { key: "solve", emoji: "🍽", label: "What should I cook today?" },
            { key: "emergency", emoji: "🆘", label: "Emergency menu" },
            { key: "under30", emoji: "⏱", label: "Recipes in 30 minutes or less" },
            { key: "snack", emoji: "🥨", label: "Quick healthy snack" },
          ],
        },
        {
          key: "week",
          title: "Organize the week",
          cards: [
            { key: "weeklyPlanner", emoji: "📅", label: "Weekly planner" },
            { key: "shoppingList", emoji: "🛒", label: "Smart shopping list" },
            { key: "portions", emoji: "🍽", label: "Servings calculator" },
            { key: "occasions", emoji: "🎉", label: "Special occasion menus" },
          ],
        },
      ],
      savedRecipesLink: "❤️ My saved recipes",
      moreOptions: "See all options",
    },
    intro: {
      message: "Hi, I'm your personal AI Chef. I'll solve today's meal for you. I only need a few details.",
      cta: "Let's do it",
    },
    people: {
      title: "How many people are eating today?",
      options: ["Just me", "2 people", "3–4 people", "5+"],
    },
    children: {
      title: "Are there children eating today?",
      yes: "Yes",
      no: "No",
      agesTitle: "What ages?",
      ages: ["0–2", "3–5", "6–9", "10–14", "15+"],
    },
    time: {
      title: "How much time do you have?",
      options: ["15 minutes", "20 minutes", "30 minutes", "45 minutes", "I have more time", "Surprise me"],
    },
    ingredients: {
      title: "What do you already have at home?",
      placeholder: "Type an ingredient and hit Enter…",
      categories: ["Meat", "Vegetables", "Dairy", "Eggs", "Pasta", "Pantry", "Fruits", "Spices"],
      suggestedLabel: "Suggested for you",
    },
    shoppingPref: {
      title: "Do you want to cook only with what you already have?",
      options: ["Yes, don't make me buy anything", "I can buy a few ingredients", "No preference"],
    },
    dietary: {
      title: "Any dietary restrictions or needs?",
      options: [
        "No restrictions", "Vegetarian", "Vegan", "Gluten-free", "Dairy-free",
        "Low sodium", "Diabetes-friendly style", "High protein", "Low carb",
        "Kid-friendly", "Light meal",
      ],
    },
    preference: {
      title: "What sounds good today?",
      options: [
        "Chicken", "Beef", "Fish", "Pasta", "Vegetarian", "Light & fresh",
        "Comfort food", "Mexican", "Mediterranean", "Asian inspired", "Surprise me",
      ],
    },
    goal: {
      title: "What matters most today?",
      options: [
        "Cook fast", "Spend less", "Eat healthier", "Use what I have",
        "More protein", "Lower calories", "Don't make me think",
      ],
    },
    thinking: {
      title: "Solving your meal…",
      lines: [
        "Analyzing your ingredients…",
        "Checking your available time…",
        "Adapting to your country…",
        "Estimating what's missing…",
        "Balancing the nutrition…",
        "Comparing cooking vs delivery…",
        "Building your best option…",
      ],
    },
    result: {
      title: "I solved dinner for you.",
      congrats: "Great choice! 🎉",
      solvedIn: "You solved your menu in {s} seconds ⚡",
      solvedInFooter: "That's how fast cooking gets when there's order.",
      servings: "servings",
      stepsLabel: "Steps",
      timeLabel: "Time",
      difficulty: "Difficulty",
      cost: "Estimated cost",
      calories: "kcal per serving",
      viewRecipe: "View recipe",
      dislike: "I don't like this",
      save: "Save / copy",
      another: "Another option",
      saveFavorite: "❤️ Save recipe",
      savedFavorite: "❤️ Saved",
    },
    why: {
      title: "Why I chose this",
    },
    pairing: {
      title: "How to enjoy it",
      side: "Pair it with",
      dessert: "For dessert",
      drink: "To drink",
    },
    actions: {
      copyRecipe: "📋 Copy recipe",
      copyShoppingList: "📋 Copy shopping list",
      more: "Want me to calculate anything else?",
      shoppingList: "Shopping list",
      calories: "Calories & nutrition",
      savings: "Delivery savings",
      anotherOption: "Another option",
      adaptRecipe: "Adapt recipe",
      discover: "Discover Cocina Sin Estrés",
    },
    reject: {
      message: "No problem. What would you like to change?",
      options: [
        { key: "faster", label: "Faster" },
        { key: "cheaper", label: "Cheaper" },
        { key: "healthier", label: "Healthier" },
        { key: "moreProtein", label: "More protein" },
        { key: "lowerCalories", label: "Lower calories" },
        { key: "differentProtein", label: "Different protein" },
        { key: "sameIngredients", label: "Same ingredients" },
        { key: "buyMore", label: "I can buy more" },
        { key: "kidFriendly", label: "Kid-friendly" },
        { key: "surpriseAgain", label: "Surprise me again" },
      ],
    },
    favorite: {
      howTitle: "How do you want to add it?",
      typePaste: "Type / paste recipe",
      pasteLink: "Paste a link",
      uploadPhoto: "Upload a photo",
      uploadPdf: "Upload a PDF",
      futurePlaceholder: "Photo and PDF analysis can be connected later. For now, paste your recipe text.",
      placeholder: "Paste your favorite recipe here…",
      adaptTitle: "How should I adapt it?",
      adaptOptions: [
        "Make it faster", "Make it healthier", "Make it cheaper", "More protein", "Lower calories",
        "Kid-friendly", "Gluten-free", "Dairy-free", "Use what I already have", "Adapt to today's family size",
      ],
      submit: "Adapt recipe →",
    },
    nutrition: {
      title: "Calories & nutrition",
      disclaimer: "Estimated values.",
      protein: "Protein",
      carbs: "Carbs",
      fat: "Fat",
      fiber: "Fiber",
      sugar: "Sugar",
      sodium: "Sodium",
      score: "Nutrition score",
      benefitsTitle: "Benefits of this dish",
    },
    savingsModule: {
      title: "Cooking vs. delivery",
      disclaimer: "Estimated savings.",
      cooking: "Cooking this",
      delivery: "Delivery estimate",
      todaySavings: "You save today",
      monthly: "Estimated monthly savings",
    },
    shoppingListModule: {
      title: "Shopping list",
      subtitle: "Only what's missing.",
      estimatedCost: "Estimated cost",
      nothingMissing: "You already have everything you need. ✅",
    },
    weeklyPlanner: {
      title: "Weekly planner",
      subtitle: "5 days solved, with a single shopping list for the whole week.",
      generatingTitle: "Building your week…",
      dayLabels: ["Day 1", "Day 2", "Day 3", "Day 4", "Day 5"],
      shoppingListTitle: "This week's shopping list",
      cta: "Build my week →",
      viewDay: "View recipe",
      backToWeek: "← Back to the week",
    },
    occasions: {
      title: "Special occasion menus",
      subtitle: "Pick the occasion and I'll put together a ready menu.",
      menuSubtitle: "Tap a recipe to see it in full.",
    },
    savedRecipes: {
      title: "My saved recipes",
      empty: "You haven't saved any recipes yet. Once you solve a meal, tap “Save recipe.”",
      remove: "Remove",
      savedToast: "Saved to My Recipes",
    },
    guide: {
      title: "Interactive guide",
      subtitle: "Short chapters to understand the method, not just use it.",
      chapters: [
        {
          title: "The real problem isn't cooking",
          body: "Daily meals become stressful because it's never just one task. It's deciding, checking ingredients, calculating time, thinking about tastes, shopping, cooking, and repeating it every single day.",
          quote: "You are not tired of cooking. You are tired of deciding what to cook.",
        },
        {
          title: "The 4 mistakes that make daily meals chaotic",
          errors: [
            "Shopping without a menu.",
            "Searching for recipes once you're already hungry.",
            "Thinking in single meals instead of blocks.",
            "Wanting to cook perfectly when you just need a simple solution.",
          ],
          quote: "Daily cooking doesn't need inspiration. It needs structure.",
        },
        {
          title: "The emergency menu",
          body: "Everyone needs simple options for the tired days — something to fall back on without thinking, without guilt, and without depending on delivery.",
          quote: "When you have an emergency menu, exhaustion stops deciding for you.",
        },
        {
          title: "How to build a week without drama",
          structure: [
            "2 base meals.",
            "2 quick meals.",
            "1 leftovers meal.",
            "1 emergency meal.",
            "1 free choice.",
          ],
          quote: "A good weekly menu doesn't box you in. It frees you from deciding while tired.",
        },
        {
          title: "An organized kitchen means faster meals",
          structure: [
            "Empty and wipe down the fridge on a fixed day each week, before you shop.",
            "Always store things in the same spot — you stop wasting time searching.",
            "Batch cook: double a recipe and freeze half in individual portions.",
            "Label what you freeze with the date, so nothing piles up unchecked.",
            "Shop for the whole week at once, not meal by meal.",
          ],
          quote: "When the kitchen has order, deciding what to cook stops being a chore.",
        },
      ],
      cta: "Back to the method",
    },
    finalCta: {
      message: "Today we solved one meal. Imagine solving your whole week like this.",
      bullets: [
        "Weekly menus", "Smart shopping lists", "Recipes based on what you have",
        "Calories & nutrition", "Kids menus", "Themed menus", "Savings calculator",
      ],
      cta: "Discover Cocina Sin Estrés →",
      secondary: "Try another recipe",
    },
    ui: {
      back: "← Back",
      backWord: "Back",
      next: "Next →",
      finish: "See my summary →",
      copied: "Copied!",
      estimatedValues: "Estimated values",
      skip: "Skip",
      continue: "Continue",
      loading: "One second…",
    },
  },
} as const;

export function t(lang: Lang) {
  return strings[lang];
}
